
calendar_medion.wad
gfx/env/3dmfallsup.tga
gfx/env/3dmfallsdn.tga
gfx/env/3dmfallslf.tga
gfx/env/3dmfallsrt.tga
gfx/env/3dmfallsft.tga
gfx/env/3dmfallsbk.tga
models/medion/aztec_remake/bush22.mdl
models/medion/aztec_remake/prop_rimpalm1a_2bone.mdl
models/medion/aztec_remake/prop_rimpalm1a.mdl
models/medion/aztec_remake/tree01.mdl
models/medion/aztec_remake/ivy01.mdl
models/medion/aztec_remake/liana3.mdl
models/medion/aztec_remake/az_plant_3.mdl
models/medion/aztec_remake/az_korni_med_x5.mdl
models/medion/aztec_remake/az_plant_2.mdl
models/medion/aztec_remake/bugs.mdl
models/medion/aztec_remake/az_plant_1.mdl
models/medion/aztec_remake/az_walldragon.mdl
models/medion/aztec_remake/az_wall_head.mdl
models/pred_plant.mdl
models/medion/aztec_remake/bush18.mdl
models/medion/aztec_remake/az_tree1.mdl
models/medion/aztec_remake/az_korni_med_x3.mdl
models/medion/aztec_remake/bush18_big.mdl
sound/medion/maya/maya_forest2.WAV
sound/medion/maya/maya_forest1.wav
sound/medion/maya/maya_forest1.WAV
models/medion/aztec_remake/grass6.mdl
models/medion/aztec_remake/az_bush2_big.mdl
sound/medion/maya/maya_forest2.wav
models/medion/aztec_remake/bush17.mdl
sprites/medion/med_flare.spr
