// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
models/AoMClassic/hornet.mdl
models/AoMClassic/items/w_ak47clip.mdl
models/AoMClassic/items/w_battery.mdl
models/AoMClassic/items/w_batteryt.mdl
models/AoMClassic/items/w_berettaclip.mdl
models/AoMClassic/items/w_berettaclipt.mdl
models/AoMClassic/items/w_deagleclip.mdl
models/AoMClassic/items/w_medkit.mdl
models/AoMClassic/lambda_custom.mdl
models/AoMClassic/monsters/twitcher/twitcher.mdl
models/AoMClassic/monsters/twitcher/twitcher01.mdl
models/AoMClassic/monsters/twitcher/twitcher02.mdl
models/AoMClassic/monsters/twitcher/twitcher03.mdl
models/AoMClassic/monsters/twitcher/twitchert.mdl
models/AoMClassic/props/flo_toilet.mdl
models/AoMClassic/weapons/ak47/p_clak47.mdl
models/AoMClassic/weapons/ak47/v_clak47.mdl
models/AoMClassic/weapons/ak47/w_clak47.mdl
models/AoMClassic/weapons/beretta/p_clberetta.mdl
models/AoMClassic/weapons/beretta/v_clberetta.mdl
models/AoMClassic/weapons/beretta/w_clberetta.mdl
models/AoMClassic/weapons/deagle/p_cldeagle.mdl
models/AoMClassic/weapons/deagle/v_cldeagle.mdl
models/AoMClassic/weapons/deagle/w_cldeagle.mdl
models/AoMClassic/weapons/knife/p_clknife.mdl
models/AoMClassic/weapons/knife/v_clknife.mdl
models/AoMClassic/weapons/knife/w_clknife.mdl
models/AoMClassic/weapons/shotgun/p_clshotgun.mdl
models/AoMClassic/weapons/shotgun/v_clshotgun.mdl
models/AoMClassic/weapons/shotgun/w_clshotgun.mdl
sound/AoMClassic/ambience/t_balkony.wav
sound/AoMClassic/ambience/t_elev.wav
sound/AoMClassic/ambience/t_kitchen.wav
sound/AoMClassic/ambience/t_outdown.wav
sound/AoMClassic/ambience/t_outdownchi.wav
sound/AoMClassic/buttons/button5.wav
sound/AoMClassic/debris/bustglass1.wav
sound/AoMClassic/debris/bustglass2.wav
sound/AoMClassic/debris/bustglass3.wav
sound/AoMClassic/debris/glass1.wav
sound/AoMClassic/debris/glass2.wav
sound/AoMClassic/debris/glass3.wav
sound/AoMClassic/debris/glass4.wav
sound/AoMClassic/debris/zap1.wav
sound/AoMClassic/debris/zap4.wav
sound/AoMClassic/doors/doormove4.wav
sound/AoMClassic/doors/doormove5.wav
sound/AoMClassic/doors/doormove6.wav
sound/AoMClassic/doors/doormove9.wav
sound/AoMClassic/doors/doorstop4.wav
sound/AoMClassic/fans/fan2.wav
sound/AoMClassic/items/flashlight1.wav
sound/AoMClassic/items/smallmedkit1.wav
sound/AoMClassic/misc/checkpoint.wav
sound/AoMClassic/monsters/face/ag_buzz1.wav
sound/AoMClassic/monsters/face/ag_hornethit1.wav
sound/AoMClassic/monsters/face/ag_hornethit2.wav
sound/AoMClassic/monsters/face/ag_hornethit3.wav
sound/AoMClassic/monsters/twitcher/zo_alert10.wav
sound/AoMClassic/monsters/twitcher/zo_alert20.wav
sound/AoMClassic/monsters/twitcher/zo_alert30.wav
sound/AoMClassic/monsters/twitcher/zo_attack1.wav
sound/AoMClassic/monsters/twitcher/zo_attack2.wav
sound/AoMClassic/monsters/twitcher/zo_pain1.wav
sound/AoMClassic/monsters/twitcher/zo_pain2.wav
sound/AoMClassic/plats/elevmove1.wav
sound/AoMClassic/weapons/ak47/ak47_boltpull.wav
sound/AoMClassic/weapons/ak47/ak47_clipin.wav
sound/AoMClassic/weapons/ak47/ak47_clipout.wav
sound/AoMClassic/weapons/ak47/ak47_fire.wav
sound/AoMClassic/weapons/ak47/ak47_stockup.wav
sound/AoMClassic/weapons/beretta/beretta_clipin.wav
sound/AoMClassic/weapons/beretta/beretta_clipout.wav
sound/AoMClassic/weapons/beretta/beretta_fire.wav
sound/AoMClassic/weapons/beretta/beretta_reload.wav
sound/AoMClassic/weapons/beretta/beretta_slide.wav
sound/AoMClassic/weapons/deagle/deagle_draw.wav
sound/AoMClassic/weapons/deagle/deagle_fire.wav
sound/AoMClassic/weapons/deagle/deagle_reload.wav
sound/AoMClassic/weapons/deagle/deagle_slide.wav
sound/AoMClassic/weapons/explode1.wav
sound/AoMClassic/weapons/knife/knife_hit1.wav
sound/AoMClassic/weapons/knife/knife_hit2.wav
sound/AoMClassic/weapons/knife/knife_hitbod1.wav
sound/AoMClassic/weapons/knife/knife_hitbod2.wav
sound/AoMClassic/weapons/knife/knife_hitbod3.wav
sound/AoMClassic/weapons/knife/knife_miss1.wav
sound/AoMClassic/weapons/shotgun/scock1.wav
sound/AoMClassic/weapons/shotgun/shotgun_draw.wav
sound/AoMClassic/weapons/shotgun/shotgun_fire.wav
sound/AoMClassic/weapons/shotgun/shotgun_holster.wav
sound/AoMClassic/weapons/shotgun/shotgun_pump.wav
sound/AoMDC/misc/checkpoint.wav
sound/weapons/dryfire.wav
sprites/320hud1.spr
sprites/320hud2.spr
sprites/AoMClassic/bigspit.spr
sprites/AoMClassic/blood.spr
sprites/AoMClassic/checkpoint.spr
sprites/AoMClassic/clak47.spr
sprites/AoMClassic/clberetta.spr
sprites/AoMClassic/cldeagle.spr
sprites/AoMClassic/clknife.spr
sprites/AoMClassic/clshotgun.spr
sprites/AoMClassic/fog5.spr
sprites/AoMClassic/glow01.spr
sprites/AoMClassic/keyicon.spr
sprites/AoMClassic/laserbeam.spr
sprites/AoMClassic/levelchange.spr
sprites/AoMClassic/mommaspit.spr
sprites/AoMClassic/mommaspout.spr
sprites/AoMClassic/muz1.spr
sprites/AoMClassic/muz4.spr
sprites/AoMClassic/muz8.spr
sprites/AoMClassic/shockwave.spr
sprites/AoMClassic/tinyspit.spr
sprites/AoMClassic/weapon_clak47.txt
sprites/AoMClassic/weapon_clberetta.txt
sprites/AoMClassic/weapon_cldeagle.txt
sprites/AoMClassic/weapon_clknife.txt
sprites/AoMClassic/weapon_clshotgun.txt
sprites/AoMClassic/xspark4.spr
