// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/darkcitybk.tga
gfx/env/darkcitydn.tga
gfx/env/darkcityft.tga
gfx/env/darkcitylf.tga
gfx/env/darkcityrt.tga
gfx/env/darkcityup.tga
models/AoMDC/items/w_battery.mdl
models/AoMDC/items/w_deagleclip.mdl
models/AoMDC/items/w_glockclip.mdl
models/AoMDC/items/w_medkit.mdl
models/AoMDC/items/w_mp5kclip.mdl
models/AoMDC/items/w_revolverrounds.mdl
models/AoMDC/lambda_custom.mdl
models/AoMDC/misc/hornet.mdl
models/AoMDC/monsters/devourer/devourer.mdl
models/AoMDC/monsters/face/face_new.mdl
models/AoMDC/monsters/ghost/ghost.mdl
models/AoMDC/monsters/ghost/ghost01.mdl
models/AoMDC/monsters/ghost/ghost02.mdl
models/AoMDC/monsters/hellhound/hellhound.mdl
models/AoMDC/monsters/twitcher/twitcher.mdl
models/AoMDC/monsters/twitcher/twitcher01.mdl
models/AoMDC/monsters/twitcher/twitcher02.mdl
models/AoMDC/monsters/twitcher/twitcher03.mdl
models/AoMDC/monsters/twitcher/twitcher4.mdl
models/AoMDC/monsters/twitcher/twitcher4t.mdl
models/AoMDC/monsters/twitcher/twitchert.mdl
models/AoMDC/weapons/axe/p_dcaxe.mdl
models/AoMDC/weapons/axe/v_dcaxe.mdl
models/AoMDC/weapons/axe/w_dcaxe.mdl
models/AoMDC/weapons/beretta/p_dcberetta.mdl
models/AoMDC/weapons/beretta/v_dcberetta.mdl
models/AoMDC/weapons/beretta/w_dcberetta.mdl
models/AoMDC/weapons/deagle/p_dcdeagle.mdl
models/AoMDC/weapons/deagle/v_dcdeagle.mdl
models/AoMDC/weapons/deagle/w_dcdeagle.mdl
models/AoMDC/weapons/glock/p_dcglock.mdl
models/AoMDC/weapons/glock/v_dcglock.mdl
models/AoMDC/weapons/glock/w_dcglock.mdl
models/AoMDC/weapons/hammer/p_dchammer.mdl
models/AoMDC/weapons/hammer/v_dchammer.mdl
models/AoMDC/weapons/hammer/w_dchammer.mdl
models/AoMDC/weapons/knife/p_dcknife.mdl
models/AoMDC/weapons/knife/v_dcknife.mdl
models/AoMDC/weapons/knife/w_dcknife.mdl
models/AoMDC/weapons/l85a1/p_dcl85a1.mdl
models/AoMDC/weapons/l85a1/v_dcl85a1.mdl
models/AoMDC/weapons/l85a1/w_dcl85a1.mdl
models/AoMDC/weapons/mp5k/p_dcmp5k.mdl
models/AoMDC/weapons/mp5k/v_dcmp5k.mdl
models/AoMDC/weapons/mp5k/w_dcmp5k.mdl
models/AoMDC/weapons/p228/p_dcp228.mdl
models/AoMDC/weapons/p228/v_dcp228.mdl
models/AoMDC/weapons/p228/w_dcp228.mdl
models/AoMDC/weapons/revolver/p_dcrevolver.mdl
models/AoMDC/weapons/revolver/v_dcrevolver.mdl
models/AoMDC/weapons/revolver/w_dcrevolver.mdl
models/AoMDC/weapons/shotgun/p_dcshotgun.mdl
models/AoMDC/weapons/shotgun/v_dcshotgun.mdl
models/AoMDC/weapons/shotgun/w_dcshotgun.mdl
models/AoMDC/weapons/uzi/p_dcuzi.mdl
models/AoMDC/weapons/uzi/v_dcuzi.mdl
models/AoMDC/weapons/uzi/w_dcuzi.mdl
sound/AoMDC/ambience/drips.wav
sound/AoMDC/ambience/sparks.wav
sound/AoMDC/aompa/sickfromsick.wav
sound/AoMDC/buttons/button1.wav
sound/AoMDC/buttons/button10.wav
sound/AoMDC/buttons/button3.wav
sound/AoMDC/buttons/button4.wav
sound/AoMDC/buttons/button5.wav
sound/AoMDC/buttons/button6.wav
sound/AoMDC/buttons/button7.wav
sound/AoMDC/buttons/button8.wav
sound/AoMDC/buttons/button9.wav
sound/AoMDC/buttons/latchlocked1.wav
sound/AoMDC/buttons/latchunlocked1.wav
sound/AoMDC/debris/bustflesh2.wav
sound/AoMDC/debris/bustglass1.wav
sound/AoMDC/debris/bustglass2.wav
sound/AoMDC/debris/bustglass3.wav
sound/AoMDC/debris/bustmetal1.wav
sound/AoMDC/debris/bustmetal2.wav
sound/AoMDC/debris/glass1.wav
sound/AoMDC/debris/glass2.wav
sound/AoMDC/debris/glass3.wav
sound/AoMDC/debris/glass4.wav
sound/AoMDC/debris/metal1.wav
sound/AoMDC/debris/metal2.wav
sound/AoMDC/debris/metal3.wav
sound/AoMDC/debris/metal4.wav
sound/AoMDC/debris/metal5.wav
sound/AoMDC/debris/metal6.wav
sound/AoMDC/debris/pushbox1.wav
sound/AoMDC/debris/pushbox2.wav
sound/AoMDC/debris/pushbox3.wav
sound/AoMDC/debris/zap1.wav
sound/AoMDC/debris/zap4.wav
sound/AoMDC/doors/doormove1.wav
sound/AoMDC/doors/doormove10.wav
sound/AoMDC/doors/doormove2.wav
sound/AoMDC/doors/doormove3.wav
sound/AoMDC/doors/doormove4.wav
sound/AoMDC/doors/doormove5.wav
sound/AoMDC/doors/doormove6.wav
sound/AoMDC/doors/doormove7.wav
sound/AoMDC/doors/doormove8.wav
sound/AoMDC/doors/doormove9.wav
sound/AoMDC/items/flashlight1.wav
sound/AoMDC/items/smallmedkit1.wav
sound/AoMDC/items/weapondrop1.wav
sound/AoMDC/misc/checkpoint.wav
sound/AoMDC/monsters/devourer/bcl_alert2.wav
sound/AoMDC/monsters/devourer/bcl_chew1.wav
sound/AoMDC/monsters/devourer/bcl_die1.wav
sound/AoMDC/monsters/devourer/bcl_die3.wav
sound/AoMDC/monsters/face/ag_alert1.wav
sound/AoMDC/monsters/face/ag_alert2.wav
sound/AoMDC/monsters/face/ag_alert3.wav
sound/AoMDC/monsters/face/ag_alert4.wav
sound/AoMDC/monsters/face/ag_alert5.wav
sound/AoMDC/monsters/face/ag_attack1.wav
sound/AoMDC/monsters/face/ag_attack2.wav
sound/AoMDC/monsters/face/ag_attack3.wav
sound/AoMDC/monsters/face/ag_buzz1.wav
sound/AoMDC/monsters/face/ag_die1.wav
sound/AoMDC/monsters/face/ag_die2.wav
sound/AoMDC/monsters/face/ag_die3.wav
sound/AoMDC/monsters/face/ag_die4.wav
sound/AoMDC/monsters/face/ag_die5.wav
sound/AoMDC/monsters/face/ag_fire1.wav
sound/AoMDC/monsters/face/ag_fire2.wav
sound/AoMDC/monsters/face/ag_fire3.wav
sound/AoMDC/monsters/face/ag_hornethit1.wav
sound/AoMDC/monsters/face/ag_hornethit2.wav
sound/AoMDC/monsters/face/ag_hornethit3.wav
sound/AoMDC/monsters/face/ag_idle1.wav
sound/AoMDC/monsters/face/ag_pain1.wav
sound/AoMDC/monsters/face/ag_pain2.wav
sound/AoMDC/monsters/face/ag_pain3.wav
sound/AoMDC/monsters/face/ag_pain4.wav
sound/AoMDC/monsters/face/ag_pain5.wav
sound/AoMDC/monsters/ghost/ear_ringing.wav
sound/AoMDC/monsters/ghost/slv_alert2.wav
sound/AoMDC/monsters/ghost/slv_die.wav
sound/AoMDC/monsters/ghost/slv_word3.wav
sound/AoMDC/monsters/ghost/slv_word4.wav
sound/AoMDC/monsters/ghost/slv_word5.wav
sound/AoMDC/monsters/ghost/slv_word7.wav
sound/AoMDC/monsters/hellhound/he_alert1.wav
sound/AoMDC/monsters/hellhound/he_alert2.wav
sound/AoMDC/monsters/hellhound/he_blast1.wav
sound/AoMDC/monsters/hellhound/he_blast2.wav
sound/AoMDC/monsters/hellhound/he_blast3.wav
sound/AoMDC/monsters/hellhound/he_die1.wav
sound/AoMDC/monsters/hellhound/he_die2.wav
sound/AoMDC/monsters/hellhound/he_die3.wav
sound/AoMDC/monsters/hellhound/he_pain1.wav
sound/AoMDC/monsters/hellhound/he_pain2.wav
sound/AoMDC/monsters/twitcher1/claw_miss1.wav
sound/AoMDC/monsters/twitcher1/claw_miss2.wav
sound/AoMDC/monsters/twitcher1/claw_strike1.wav
sound/AoMDC/monsters/twitcher1/claw_strike2.wav
sound/AoMDC/monsters/twitcher1/claw_strike3.wav
sound/AoMDC/monsters/twitcher1/zo_alert10.wav
sound/AoMDC/monsters/twitcher1/zo_alert20.wav
sound/AoMDC/monsters/twitcher1/zo_alert30.wav
sound/AoMDC/monsters/twitcher1/zo_attack1.wav
sound/AoMDC/monsters/twitcher1/zo_attack2.wav
sound/AoMDC/monsters/twitcher1/zo_idle1.wav
sound/AoMDC/monsters/twitcher1/zo_pain1.wav
sound/AoMDC/monsters/twitcher1/zo_pain2.wav
sound/AoMDC/monsters/twitcher2/claw_miss1.wav
sound/AoMDC/monsters/twitcher2/claw_miss2.wav
sound/AoMDC/monsters/twitcher2/claw_strike1.wav
sound/AoMDC/monsters/twitcher2/claw_strike2.wav
sound/AoMDC/monsters/twitcher2/claw_strike3.wav
sound/AoMDC/monsters/twitcher2/zo_alert10.wav
sound/AoMDC/monsters/twitcher2/zo_alert20.wav
sound/AoMDC/monsters/twitcher2/zo_alert30.wav
sound/AoMDC/monsters/twitcher2/zo_attack1.wav
sound/AoMDC/monsters/twitcher2/zo_attack2.wav
sound/AoMDC/monsters/twitcher2/zo_idle1.wav
sound/AoMDC/monsters/twitcher2/zo_pain1.wav
sound/AoMDC/monsters/twitcher2/zo_pain2.wav
sound/AoMDC/plats/elevmove1.wav
sound/AoMDC/weapons/axe/axe_hit.wav
sound/AoMDC/weapons/axe/axe_hitbody.wav
sound/AoMDC/weapons/axe/axe_swing.wav
sound/AoMDC/weapons/beretta/beretta_fire.wav
sound/AoMDC/weapons/beretta/beretta_magin.wav
sound/AoMDC/weapons/beretta/beretta_magout.wav
sound/AoMDC/weapons/beretta/beretta_magplace.wav
sound/AoMDC/weapons/beretta/beretta_slideforward.wav
sound/AoMDC/weapons/deagle/deagle_clipin.wav
sound/AoMDC/weapons/deagle/deagle_clipout.wav
sound/AoMDC/weapons/deagle/deagle_fire.wav
sound/AoMDC/weapons/deagle/deagle_slide.wav
sound/AoMDC/weapons/explode3.wav
sound/AoMDC/weapons/glock/glock_fire.wav
sound/AoMDC/weapons/glock/glock_magin.wav
sound/AoMDC/weapons/glock/glock_magout.wav
sound/AoMDC/weapons/glock/glock_magplace.wav
sound/AoMDC/weapons/glock/glock_slideforward.wav
sound/AoMDC/weapons/hammer/hammer_hit.wav
sound/AoMDC/weapons/hammer/hammer_hitbody.wav
sound/AoMDC/weapons/hammer/hammer_miss.wav
sound/AoMDC/weapons/knife/knife_hit1.wav
sound/AoMDC/weapons/knife/knife_hit2.wav
sound/AoMDC/weapons/knife/knife_swing1.wav
sound/AoMDC/weapons/knife/knife_wall1.wav
sound/AoMDC/weapons/knife/knife_wall2.wav
sound/AoMDC/weapons/l85a1/l85a1_fire.wav
sound/AoMDC/weapons/mp5k/mp5k_boltback.wav
sound/AoMDC/weapons/mp5k/mp5k_boltforward.wav
sound/AoMDC/weapons/mp5k/mp5k_fire.wav
sound/AoMDC/weapons/mp5k/mp5k_magin.wav
sound/AoMDC/weapons/mp5k/mp5k_magout.wav
sound/AoMDC/weapons/p228/p228_fire.wav
sound/AoMDC/weapons/p228/p228_magin.wav
sound/AoMDC/weapons/p228/p228_magout.wav
sound/AoMDC/weapons/p228/p228_magplace.wav
sound/AoMDC/weapons/p228/p228_slideforward.wav
sound/AoMDC/weapons/revolver/revolver_draw.wav
sound/AoMDC/weapons/revolver/revolver_fire.wav
sound/AoMDC/weapons/revolver/revolver_reload.wav
sound/AoMDC/weapons/shotgun/shotgun_fire.wav
sound/AoMDC/weapons/shotgun/shotgun_insert.wav
sound/AoMDC/weapons/shotgun/shotgun_pump.wav
sound/AoMDC/weapons/shotgun/sshell1.wav
sound/AoMDC/weapons/shotgun/sshell2.wav
sound/AoMDC/weapons/shotgun/sshell3.wav
sound/AoMDC/weapons/uzi/uzi_boltpull.wav
sound/AoMDC/weapons/uzi/uzi_fire.wav
sound/AoMDC/weapons/uzi/uzi_magin.wav
sound/AoMDC/weapons/uzi/uzi_magout.wav
sound/blackdog/dog_run.wav
sound/weapons/dryfire.wav
sprites/320hud1.spr
sprites/320hud2.spr
sprites/AoMDC/bigspit.spr
sprites/AoMDC/dcaxe.spr
sprites/AoMDC/dcberetta.spr
sprites/AoMDC/dcdeagle.spr
sprites/AoMDC/dcglock.spr
sprites/AoMDC/dchammer.spr
sprites/AoMDC/dcknife.spr
sprites/AoMDC/dcl85a1.spr
sprites/AoMDC/dcmp5k.spr
sprites/AoMDC/dcp228.spr
sprites/AoMDC/dcrevolver.spr
sprites/AoMDC/dcshotgun.spr
sprites/AoMDC/dcuzi.spr
sprites/AoMDC/fog5.spr
sprites/AoMDC/keyicon.spr
sprites/AoMDC/laserbeam.spr
sprites/AoMDC/mommaspit.spr
sprites/AoMDC/mommaspout.spr
sprites/AoMDC/moths.spr
sprites/AoMDC/muz1.spr
sprites/AoMDC/muz4.spr
sprites/AoMDC/ropeicon.spr
sprites/AoMDC/shockwave.spr
sprites/AoMDC/tinyspit.spr
sprites/AoMDC/weapon_dcaxe.txt
sprites/AoMDC/weapon_dcberetta.txt
sprites/AoMDC/weapon_dcdeagle.txt
sprites/AoMDC/weapon_dcglock.txt
sprites/AoMDC/weapon_dchammer.txt
sprites/AoMDC/weapon_dcknife.txt
sprites/AoMDC/weapon_dcl85a1.txt
sprites/AoMDC/weapon_dcmp5k.txt
sprites/AoMDC/weapon_dcp228.txt
sprites/AoMDC/weapon_dcrevolver.txt
sprites/AoMDC/weapon_dcshotgun.txt
sprites/AoMDC/weapon_dcuzi.txt
sprites/AoMDC/xspark4.spr
sprites/AoMDC/z_levelchange.spr
