sprites/hl_weapons/weapon_hl357.txt
models/player/combine_soldier_camo_3/combine_soldier_camo_3.mdl
models/player/combine_soldier_green/combine_soldier_green.bmp
models/player/combine_soldier_green/combine_soldier_green.mdl
models/player/combine_soldier_leak/combine_soldier_leak.bmp
models/player/combine_soldier_leak/combine_soldier_leak.mdl
models/player/combine_soldier_orange/combine_soldier_orange.bmp
models/player/combine_soldier_orange/combine_soldier_orange.mdl
models/player/combine_soldier_urban/combine_soldier_urban.bmp
models/player/combine_soldier_urban/combine_soldier_urban.mdl
models/player/comtrooper/comtrooper.bmp
models/player/comtrooper/comtrooper.mdl
models/player/conejo/conejo.bmp
models/player/conejo/conejo.mdl
models/player/cooking_mama/cooking_mama.bmp
models/player/cooking_mama/cooking_mama.mdl
models/player/cooking_mama/cooking_mama.txt
models/player/cop/cop.bmp
models/player/cop/cop.mdl
models/player/Corona_chan/corona_chan.bmp
models/player/Corona_chan/Corona_chan.mdl
