sprites/hl_weapons/weapon_hl357.txt
models/player/csx_us_galB3/csx_us_galB3.mdl
models/player/CS_Arctic/CS_Arctic.bmp
models/player/CS_Arctic/CS_Arctic.mdl
models/player/CS_GIGN/CS_GIGN.bmp
models/player/CS_GIGN/CS_GIGN.mdl
models/player/CS_GSG9/CS_GSG9.bmp
models/player/CS_GSG9/CS_GSG9.mdl
models/player/CS_SAS/CS_SAS.bmp
models/player/CS_SAS/CS_SAS.mdl
models/player/CS_SEAL/CS_SEAL.bmp
models/player/CS_SEAL/CS_SEAL.mdl
models/player/CyberTrooper/CyberTrooper.bmp
models/player/CyberTrooper/CyberTrooper.mdl
models/player/D3Marine/D3Marine.bmp
models/player/D3Marine/D3Marine.mdl
models/player/Daveen_Leatherhoff/Daveen_Leatherhoff.bmp
models/player/Daveen_Leatherhoff/Daveen_Leatherhoff.mdl
models/player/david/david.bmp
models/player/david/david.mdl
models/player/davidbad/davidbad.bmp
