sprites/hl_weapons/weapon_hl357.txt
models/player/csx_schoolgirl/csx_schoolgirl.mdl
models/player/csx_seal/csx_seal.bmp
models/player/csx_seal/csx_seal.mdl
models/player/csx_seal2/csx_seal2.bmp
models/player/csx_seal2/csx_seal2.mdl
models/player/csx_seal3/csx_seal3.bmp
models/player/csx_seal3/csx_seal3.mdl
models/player/csx_seal4/csx_seal4.bmp
models/player/csx_seal4/csx_seal4.mdl
models/player/csx_seal5/csx_seal5.bmp
models/player/csx_seal5/csx_seal5.mdl
models/player/csx_seal6/csx_seal6.bmp
models/player/csx_seal6/csx_seal6.mdl
models/player/csx_seal7/csx_seal7.bmp
models/player/csx_seal7/csx_seal7.mdl
models/player/csx_seal8/csx_seal8.bmp
models/player/csx_seal8/csx_seal8.mdl
models/player/csx_spetsnaz/csx_spetsnaz.bmp
models/player/csx_spetsnaz/csx_spetsnaz.mdl
models/player/csx_spetsnaz2/csx_spetsnaz2.bmp
