sprites/hl_weapons/weapon_hl357.txt
models/player/csx_guerilla2/csx_guerilla2.mdl
models/player/csx_guerilla3/csx_guerilla3.bmp
models/player/csx_guerilla3/csx_guerilla3.mdl
models/player/csx_guerilla4/csx_guerilla4.bmp
models/player/csx_guerilla4/csx_guerilla4.mdl
models/player/csx_guerilla5/csx_guerilla5.bmp
models/player/csx_guerilla5/csx_guerilla5.mdl
models/player/csx_guerilla6/csx_guerilla6.bmp
models/player/csx_guerilla6/csx_guerilla6.mdl
models/player/csx_guerilla7/csx_guerilla7.bmp
models/player/csx_guerilla7/csx_guerilla7.mdl
models/player/csx_hostageA/csx_hostageA.bmp
models/player/csx_hostageA/csx_hostageA.mdl
models/player/csx_hostageB/csx_hostageB.bmp
models/player/csx_hostageB/csx_hostageB.mdl
models/player/csx_hostageC/csx_hostageC.bmp
models/player/csx_hostageC/csx_hostageC.mdl
models/player/csx_hostageD/csx_hostageD.bmp
models/player/csx_hostageD/csx_hostageD.mdl
models/player/csx_jumpsuit/csx_jumpsuit.bmp
