sprites/hl_weapons/weapon_hl357.txt
models/player/csx_spetsnaz2/csx_spetsnaz2.mdl
models/player/csx_spetsnaz3/csx_spetsnaz3.bmp
models/player/csx_spetsnaz3/csx_spetsnaz3.mdl
models/player/csx_terror/csx_terror.bmp
models/player/csx_terror/csx_terror.mdl
models/player/csx_terror2/csx_terror2.bmp
models/player/csx_terror2/csx_terror2.mdl
models/player/csx_terror3/csx_terror3.bmp
models/player/csx_terror3/csx_terror3.mdl
models/player/csx_us_galA1/csx_us_galA1.bmp
models/player/csx_us_galA1/csx_us_galA1.mdl
models/player/csx_us_galA2/csx_us_galA2.bmp
models/player/csx_us_galA2/csx_us_galA2.mdl
models/player/csx_us_galA3/csx_us_galA3.bmp
models/player/csx_us_galA3/csx_us_galA3.mdl
models/player/csx_us_galB1/csx_us_galB1.bmp
models/player/csx_us_galB1/csx_us_galB1.mdl
models/player/csx_us_galB2/csx_us_galB2.bmp
models/player/csx_us_galB2/csx_us_galB2.mdl
models/player/csx_us_galB3/csx_us_galB3.bmp
