sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/DoD_G_RF_NH/DoD_G_RF_NH.mdl
models/player/DoD_G_SN_NH/DoD_G_SN_NH.bmp
models/player/DoD_G_SN_NH/DoD_G_SN_NH.mdl
models/player/DoD_G_SU_NH/DoD_G_SU_NH.bmp
models/player/DoD_G_SU_NH/DoD_G_SU_NH.mdl
models/player/don7t0get0suprised.txt
models/player/doomguy/doomguy.bmp
models/player/doomguy/doomguy.mdl
models/player/doomguyunmask/doomguyunmask.bmp
models/player/doomguyunmask/doomguyunmask.mdl
models/player/doomguyunmask_black/doomguyunmask_black.bmp
models/player/doomguyunmask_black/doomguyunmask_black.mdl
models/player/doomguyunmask_white/doomguyunmask_white.bmp
models/player/doomguyunmask_white/doomguyunmask_white.mdl
models/player/doomguy_2/doomguy_2.bmp
models/player/doomguy_2/doomguy_2.mdl
models/player/doomguy_2black/doomguy_2black.bmp
models/player/doomguy_2black/doomguy_2black.mdl
models/player/doomguy_2white/doomguy_2white.bmp
models/player/doomguy_2white/doomguy_2white.mdl
