sprites/hl_weapons/weapon_hl357.txt
models/player/doomguy_black/doomguy_black.bmp
models/player/doomguy_black/doomguy_black.mdl
models/player/doomguy_white/doomguy_white.bmp
models/player/doomguy_white/doomguy_white.mdl
models/player/DOTSO_Erio/DOTSO_Erio.bmp
models/player/DOTSO_Erio/DOTSO_Erio.mdl
models/player/DrEggman/DrEggman.bmp
models/player/DrEggman/DrEggman.mdl
models/player/droid_hd/droid.bmp
models/player/droid_hd/droid_hd.mdl
models/player/DS1_issac/DS1_issac.bmp
models/player/DS1_issac/DS1_issac.mdl
models/player/DS2_issac/DS2_issac.bmp
models/player/DS2_issac/DS2_issac.mdl
models/player/duke/duke.bmp
models/player/duke/duke.mdl
models/player/dunmer/dunmer.bmp
models/player/dunmer/dunmer.mdl
models/player/dusk_leatherneck/Dusk_leatherneck.bmp
models/player/dusk_leatherneck/Dusk_leatherneck.mdl
