sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/giacomo_2/giacomo_2.mdl
models/player/gign/gign.bmp
models/player/gign/gign.mdl
models/player/Giorno/giorno.bmp
models/player/Giorno/giorno.mdl
models/player/GI_Ayaka/GI_Ayaka.bmp
models/player/GI_Ayaka/GI_Ayaka.mdl
models/player/gi_barbara/GI_Barbara.bmp
models/player/gi_barbara/GI_Barbara.mdl
models/player/GI_Diona/GI_Diona.bmp
models/player/GI_Diona/GI_Diona.mdl
models/player/GI_Diona_Meranian/GI_Diona_Meranian.bmp
models/player/GI_Diona_Meranian/GI_Diona_Meranian.mdl
models/player/GI_Ganyu/GI_Ganyu.bmp
models/player/GI_Ganyu/GI_Ganyu.mdl
models/player/GI_Ganyu/GI_Ganyu_ragdoll.txt
models/player/gi_hutao/GI_HuTao.bmp
models/player/gi_hutao/GI_HuTao.mdl
models/player/GI_Keqing/GI_Keqing.bmp
models/player/GI_Keqing/GI_Keqing.mdl
