sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/GFL_AK12_alt2/GFL_AK12_alt2.mdl
models/player/GFL_HK416/GFL_HK416.bmp
models/player/GFL_HK416/GFL_HK416.mdl
models/player/GFL_M14/GFL_M14.bmp
models/player/GFL_M14/GFL_M14.mdl
models/player/GFL_M14-c2/GFL_M14-c2.bmp
models/player/GFL_M14-c2/GFL_M14-c2.mdl
models/player/GFL_M4A1/GFL_M4A1.bmp
models/player/GFL_M4A1/GFL_M4A1.mdl
models/player/GFL_M4_Sopmod/GFL_M4_Sopmod.bmp
models/player/GFL_M4_Sopmod/GFL_M4_Sopmod.mdl
models/player/GFL_M4_Sopmod-c2/GFL_M4_Sopmod-c2.bmp
models/player/GFL_M4_Sopmod-c2/GFL_M4_Sopmod-c2.mdl
models/player/GFL_Negev/GFL_Negev.bmp
models/player/GFL_Negev/GFL_Negev.mdl
models/player/GFL_Negev_shoeless/GFL_Negev_shoeless.bmp
models/player/GFL_Negev_shoeless/GFL_Negev_shoeless.mdl
models/player/GFL_UMP45/GFL_UMP45.bmp
models/player/GFL_UMP45/GFL_UMP45.mdl
models/player/GFL_UMP45-c2/GFL_UMP45-c2.bmp
