sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/GFL_UMP45-c2/GFL_UMP45-c2.mdl
models/player/GFL_UMP9/GFL_UMP9.bmp
models/player/GFL_UMP9/GFL_UMP9.mdl
models/player/GFL_UMP9-c2/GFL_UMP9-c2.bmp
models/player/GFL_UMP9-c2/GFL_UMP9-c2.mdl
models/player/gf_9a-91/GF_9A-91.bmp
models/player/gf_9a-91/GF_9A-91.mdl
models/player/GF_G11/GF_G11.bmp
models/player/GF_G11/GF_G11.mdl
models/player/GF_IDW/GF_IDW.bmp
models/player/GF_IDW/GF_IDW.mdl
models/player/GF_UMP45/GF_UMP45.bmp
models/player/GF_UMP45/GF_UMP45.mdl
models/player/GF_UMP9/GF_UMP9.bmp
models/player/GF_UMP9/GF_UMP9.mdl
models/player/ghost_sniper/ghost_sniper.bmp
models/player/ghost_sniper/ghost_sniper.mdl
models/player/giacomo/giacomo.bmp
models/player/giacomo/giacomo.mdl
models/player/giacomo_2/giacomo_2.bmp
