//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_dust2_winter.html
halflife.wad
sound/ambience/wind1.wav
overviews/de_dust2_winter.txt
sound/ambience/wind.wav
gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
maps/de_dust2_winter.bsp
maps/de_dust2_winter.txt
