// Created with resguy v7 (December 2017)
// https://github.com/wootguy/resguy

doom2_b3.wad
gfx/env/rsky1_bk.tga
gfx/env/rsky1_dn.tga
gfx/env/rsky1_ft.tga
gfx/env/rsky1_lf.tga
gfx/env/rsky1_rt.tga
gfx/env/rsky1_up.tga
models/custom_weapons/cs16/p_chainsaw.mdl
models/custom_weapons/cs16/p_m1887.mdl
models/doom/null.mdl
models/doom/null_fat.mdl
models/doom/null_huge.mdl
models/doom/null_large.mdl
models/doom/null_spider.mdl
models/doom/null_tall.mdl
models/doom/null_wide.mdl
sound/doom/between_levels.ogg
sound/doom/countdown_to_death.ogg
sound/doom/doom.ogg
sound/doom/dsbarexp.wav
sound/doom/dsbdcls.wav
sound/doom/dsbdopn.wav
sound/doom/dsbfg.wav
sound/doom/dsbgact.wav
sound/doom/dsbgdth1.wav
sound/doom/dsbgdth2.wav
sound/doom/dsbgsit1.wav
sound/doom/dsbgsit2.wav
sound/doom/dsbrsdth.wav
sound/doom/dsbrssit.wav
sound/doom/dsbspact.wav
sound/doom/dsbspdth.wav
sound/doom/dsbspsit.wav
sound/doom/dsbspwlk.wav
sound/doom/dscacdth.wav
sound/doom/dscacsit.wav
sound/doom/dsclaw.wav
sound/doom/dscybdth.wav
sound/doom/dscybsit.wav
sound/doom/dsdmact.wav
sound/doom/dsdmpain.wav
sound/doom/dsdorcls.wav
sound/doom/dsdoropn.wav
sound/doom/dsfirsht.wav
sound/doom/dsfirxpl.wav
sound/doom/dsflame.wav
sound/doom/dsgetpow.wav
sound/doom/dshoof.wav
sound/doom/dsitemup.wav
sound/doom/dsitmbk.wav
sound/doom/dskntdth.wav
sound/doom/dskntsit.wav
sound/doom/dsmandth.wav
sound/doom/dsmansit.wav
sound/doom/dsmetal.wav
sound/doom/dsmnpain.wav
sound/doom/dspdiehi.wav
sound/doom/dspedth.wav
sound/doom/dspepain.wav
sound/doom/dspesit.wav
sound/doom/dspistol.wav
sound/doom/dsplasma.wav
sound/doom/dspldeth.wav
sound/doom/dsplpain.wav
sound/doom/dspodth1.wav
sound/doom/dspodth2.wav
sound/doom/dspodth3.wav
sound/doom/dspopain.wav
sound/doom/dsposact.wav
sound/doom/dsposit1.wav
sound/doom/dsposit2.wav
sound/doom/dsposit3.wav
sound/doom/dspstart.wav
sound/doom/dspstop.wav
sound/doom/dspunch.wav
sound/doom/dsrlaunc.wav
sound/doom/dsrxplod.wav
sound/doom/dssawful.wav
sound/doom/dssawhit.wav
sound/doom/dssawidl.wav
sound/doom/dssawup.wav
sound/doom/dssecret.wav
sound/doom/dssgtatk.wav
sound/doom/dssgtdth.wav
sound/doom/dssgtsit.wav
sound/doom/dsshotgn.wav
sound/doom/dsskeact.wav
sound/doom/dsskeatk.wav
sound/doom/dsskedth.wav
sound/doom/dsskepch.wav
sound/doom/dsskesit.wav
sound/doom/dsskeswg.wav
sound/doom/dssklatk.wav
sound/doom/dsskldth.wav
sound/doom/dsslop.wav
sound/doom/dsspidth.wav
sound/doom/dsspisit.wav
sound/doom/dsstnmov.wav
sound/doom/dsswtchn.wav
sound/doom/dsswtchx.wav
sound/doom/dstelept.wav
sound/doom/dsvilact.wav
sound/doom/dsvilatk.wav
sound/doom/dsvildth.wav
sound/doom/dsvilsit.wav
sound/doom/dsvipain.wav
sound/doom/dswpnup.wav
sound/doom/episode.ogg
sound/doom/in_the_dark.ogg
sound/doom/intermission.ogg
sound/doom/running_from_evil.ogg
sound/doom/sandy_city.ogg
sound/doom/shawn_shotgun.ogg
sound/doom/supershot.wav
sound/doom/taylor_blues.ogg
sound/doom/the_demons_dead.ogg
sound/doom/the_healer_stalks.ogg
sprites/doom/bal.spr
sprites/doom/bal7.spr
sprites/doom/bfe2.spr
sprites/doom/bfg.spr
sprites/doom/blud.spr
sprites/doom/bos2.spr
sprites/doom/boss.spr
sprites/doom/bspi.spr
sprites/doom/chaingun.spr
sprites/doom/chainsaw.spr
sprites/doom/cpos.spr
sprites/doom/cybr.spr
sprites/doom/fatb.spr
sprites/doom/fatt.spr
sprites/doom/fire.spr
sprites/doom/fist.spr
sprites/doom/head.spr
sprites/doom/keys.spr
sprites/doom/manf.spr
sprites/doom/misl.spr
sprites/doom/objects.spr
sprites/doom/pain.spr
sprites/doom/pistol.spr
sprites/doom/plasmagun.spr
sprites/doom/poss.spr
sprites/doom/puff.spr
sprites/doom/rpg.spr
sprites/doom/sarg.spr
sprites/doom/shotgun.spr
sprites/doom/skel.spr
sprites/doom/skul.spr
sprites/doom/spid.spr
sprites/doom/spos.spr
sprites/doom/supershot.spr
sprites/doom/text.spr
sprites/doom/tfog.spr
sprites/doom/troo.spr
sprites/doom/vile.spr
sprites/doom/weapon_doom_bfg.txt
sprites/doom/weapon_doom_chaingun.txt
sprites/doom/weapon_doom_chainsaw.txt
sprites/doom/weapon_doom_fist.txt
sprites/doom/weapon_doom_pistol.txt
sprites/doom/weapon_doom_plasmagun.txt
sprites/doom/weapon_doom_rpg.txt
sprites/doom/weapon_doom_shotgun.txt
sprites/doom/weapon_doom_supershot.txt
