// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/cubemath/chars/d0.mdl
models/cubemath/chars/d5.mdl
models/cubemath/chars/percent.mdl
models/decay/obj_pipe1_straight.mdl
models/decay/pipe_1_curve.mdl
models/decay/pipe_1_straight.mdl
models/decay/scientist.mdl
models/decay/scientist_rosenberg.mdl
sound/decay/ambience/decaytheme.mp3
sound/decay/barney/ba_pok0.wav
sound/decay/barney/ba_pok1.wav
sound/decay/barney/ba_pok2.wav
sound/decay/barney/ba_pok3.wav
sound/decay/colette/colette_attack0.wav
sound/decay/colette/colette_attack1.wav
sound/decay/colette/colette_attack2.wav
sound/decay/colette/colette_attack3.wav
sound/decay/colette/colette_attacked0.wav
sound/decay/colette/colette_attacked1.wav
sound/decay/colette/colette_attacked2.wav
sound/decay/colette/colette_attacked3.wav
sound/decay/colette/colette_die0.wav
sound/decay/colette/colette_die1.wav
sound/decay/colette/colette_die2.wav
sound/decay/colette/colette_kill0.wav
sound/decay/colette/colette_kill1.wav
sound/decay/colette/colette_kill2.wav
sound/decay/colette/colette_kill3.wav
sound/decay/colette/colette_kill4.wav
sound/decay/colette/colette_mad0.wav
sound/decay/colette/colette_mad1.wav
sound/decay/colette/colette_mad2.wav
sound/decay/colette/colette_pain0.wav
sound/decay/colette/colette_pain1.wav
sound/decay/colette/colette_pain2.wav
sound/decay/colette/colette_pain3.wav
sound/decay/colette/colette_stop0.wav
sound/decay/colette/colette_stop1.wav
sound/decay/colette/colette_stop2.wav
sound/decay/colette/colette_unuse0.wav
sound/decay/colette/colette_unuse1.wav
sound/decay/colette/colette_unuse2.wav
sound/decay/colette/colette_unuse3.wav
sound/decay/colette/colette_unuse4.wav
sound/decay/colette/colette_use0.wav
sound/decay/colette/colette_use1.wav
sound/decay/colette/colette_use2.wav
sound/decay/colette/colette_use3.wav
sound/decay/colette/colette_use4.wav
sound/decay/colette/colette_use5.wav
sound/decay/gina/gina_attack0.wav
sound/decay/gina/gina_attack1.wav
sound/decay/gina/gina_attack2.wav
sound/decay/gina/gina_attack3.wav
sound/decay/gina/gina_attacked0.wav
sound/decay/gina/gina_attacked1.wav
sound/decay/gina/gina_attacked2.wav
sound/decay/gina/gina_attacked3.wav
sound/decay/gina/gina_die0.wav
sound/decay/gina/gina_die1.wav
sound/decay/gina/gina_die2.wav
sound/decay/gina/gina_kill0.wav
sound/decay/gina/gina_kill1.wav
sound/decay/gina/gina_kill2.wav
sound/decay/gina/gina_kill3.wav
sound/decay/gina/gina_kill4.wav
sound/decay/gina/gina_mad0.wav
sound/decay/gina/gina_mad1.wav
sound/decay/gina/gina_mad2.wav
sound/decay/gina/gina_pain0.wav
sound/decay/gina/gina_pain1.wav
sound/decay/gina/gina_pain2.wav
sound/decay/gina/gina_pain3.wav
sound/decay/gina/gina_stop0.wav
sound/decay/gina/gina_stop1.wav
sound/decay/gina/gina_stop2.wav
sound/decay/gina/gina_unuse0.wav
sound/decay/gina/gina_unuse1.wav
sound/decay/gina/gina_unuse2.wav
sound/decay/gina/gina_unuse3.wav
sound/decay/gina/gina_unuse4.wav
sound/decay/gina/gina_use0.wav
sound/decay/gina/gina_use1.wav
sound/decay/gina/gina_use2.wav
sound/decay/gina/gina_use3.wav
sound/decay/gina/gina_use4.wav
sound/decay/gina/gina_use5.wav
sound/decay/hgrunt/ht05_halfway.wav
sound/decay/hgrunt/ht07_dontknow.wav
sound/decay/hgrunt/ht07_tracking.wav
sound/decay/keller/dk_01_cascade.wav
sound/decay/keller/dk_01_collapsed.wav
sound/decay/keller/dk_01_concern.wav
sound/decay/keller/dk_01_decision.wav
sound/decay/keller/dk_01_failed.wav
sound/decay/keller/dk_01_finished.wav
sound/decay/keller/dk_01_gonewrong.wav
sound/decay/keller/dk_01_goodgrief.wav
sound/decay/keller/dk_01_gottodeal.wav
sound/decay/keller/dk_01_kleiner.wav
sound/decay/keller/dk_01_late.wav
sound/decay/keller/dk_01_needspect.wav
sound/decay/keller/dk_01_plan.wav
sound/decay/keller/dk_01_rosenberg.wav
sound/decay/keller/dk_01_shortcut.wav
sound/decay/keller/dk_01_spectrom.wav
sound/decay/keller/dk_01_started.wav
sound/decay/keller/dk_01_storage.wav
sound/decay/keller/dk_01_survived.wav
sound/decay/keller/dk_01_tolman.wav
sound/decay/keller/dk_01_yesgood.wav
sound/decay/keller/dk_03_notime.wav
sound/decay/keller/dk_04_bewary.wav
sound/decay/keller/dk_04_bringtram.wav
sound/decay/keller/dk_04_bulkhead.wav
sound/decay/keller/dk_04_disenergy.wav
sound/decay/keller/dk_04_excellent.wav
sound/decay/keller/dk_04_goonway.wav
sound/decay/keller/dk_04_ididit.wav
sound/decay/keller/dk_04_interfere.wav
sound/decay/keller/dk_04_letssee.wav
sound/decay/keller/dk_04_monsters.wav
sound/decay/keller/dk_04_onwaythen.wav
sound/decay/keller/dk_04_otherdamp.wav
sound/decay/keller/dk_04_primlock.wav
sound/decay/keller/dk_04_primreset.wav
sound/decay/keller/dk_04_resetdamp.wav
sound/decay/keller/dk_04_resetnow.wav
sound/decay/keller/dk_04_secfirst.wav
sound/decay/keller/dk_04_testing.wav
sound/decay/keller/dk_04_toomuch.wav
sound/decay/keller/dk_04_transmit.wav
sound/decay/keller/dk_04_weakspot.wav
sound/decay/keller/dk_05_gladalive.wav
sound/decay/keller/dk_05_gotodorms.wav
sound/decay/keller/dk_05_havecode.wav
sound/decay/keller/dk_05_haveguard.wav
sound/decay/keller/dk_05_mustseal.wav
sound/decay/keller/dk_05_needcodes.wav
sound/decay/keller/dk_05_needguard.wav
sound/decay/keller/dk_05_nofoolish.wav
sound/decay/keller/dk_05_onceorbit.wav
sound/decay/keller/dk_05_otherside.wav
sound/decay/keller/dk_07_basement.wav
sound/decay/keller/dk_07_lockout.wav
sound/decay/keller/dk_07_online.wav
sound/decay/keller/dk_10_beacon.wav
sound/decay/keller/dk_10_gammalabs.wav
sound/decay/keller/dk_10_goingon.wav
sound/decay/keller/dk_10_jammed.wav
sound/decay/keller/dk_10_receiving.wav
sound/decay/keller/dk_10_working.wav
sound/decay/keller/dk_11_activate.wav
sound/decay/keller/dk_11_bothin.wav
sound/decay/keller/dk_11_elevator.wav
sound/decay/keller/dk_11_goodwork.wav
sound/decay/keller/dk_11_greatdone.wav
sound/decay/keller/dk_11_matrixact.wav
sound/decay/keller/dk_11_unlock.wav
sound/decay/keller/dk_11_upstairs.wav
sound/decay/keller/dk_12_allactive.wav
sound/decay/keller/dk_12_attbeacon.wav
sound/decay/keller/dk_12_beacon1.wav
sound/decay/keller/dk_12_blastbunker.wav
sound/decay/keller/dk_12_bunker.wav
sound/decay/keller/dk_12_bunkerfail.wav
sound/decay/keller/dk_12_bunkeropen.wav
sound/decay/keller/dk_12_critical1.wav
sound/decay/keller/dk_12_critical2.wav
sound/decay/keller/dk_12_deploy1.wav
sound/decay/keller/dk_12_destroy.wav
sound/decay/keller/dk_12_donewell.wav
sound/decay/keller/dk_12_dontcare.wav
sound/decay/keller/dk_12_failed.wav
sound/decay/keller/dk_12_final100.wav
sound/decay/keller/dk_12_final20.wav
sound/decay/keller/dk_12_final75.wav
sound/decay/keller/dk_12_first100.wav
sound/decay/keller/dk_12_firstgo.wav
sound/decay/keller/dk_12_followme.wav
sound/decay/keller/dk_12_iiii.wav
sound/decay/keller/dk_12_mindopen.wav
sound/decay/keller/dk_12_mountgun.wav
sound/decay/keller/dk_12_netting.wav
sound/decay/keller/dk_12_radio.wav
sound/decay/keller/dk_12_second100.wav
sound/decay/keller/dk_12_second50.wav
sound/decay/keller/dk_12_second80.wav
sound/decay/keller/dk_12_second90.wav
sound/decay/keller/dk_12_success.wav
sound/decay/keller/dk_12_surge.wav
sound/decay/keller/dk_12_thisisbad.wav
sound/decay/keller/dk_12_wedidit.wav
sound/decay/keller/dk_12_whenstart.wav
sound/decay/keller/dk_condolences.wav
sound/decay/keller/dk_die1.wav
sound/decay/keller/dk_die2.wav
sound/decay/keller/dk_die3.wav
sound/decay/keller/dk_die4.wav
sound/decay/keller/dk_die5.wav
sound/decay/keller/dk_die6.wav
sound/decay/keller/dk_die7.wav
sound/decay/keller/dk_fear0.wav
sound/decay/keller/dk_fear1.wav
sound/decay/keller/dk_fear2.wav
sound/decay/keller/dk_fear3.wav
sound/decay/keller/dk_fear4.wav
sound/decay/keller/dk_fear5.wav
sound/decay/keller/dk_fear6.wav
sound/decay/keller/dk_furher.wav
sound/decay/keller/dk_hello0.wav
sound/decay/keller/dk_hello1.wav
sound/decay/keller/dk_hello2.wav
sound/decay/keller/dk_hello3.wav
sound/decay/keller/dk_hello4.wav
sound/decay/keller/dk_help0.wav
sound/decay/keller/dk_help1.wav
sound/decay/keller/dk_help2.wav
sound/decay/keller/dk_hevchair.wav
sound/decay/keller/dk_idle0.wav
sound/decay/keller/dk_idle1.wav
sound/decay/keller/dk_idle2.wav
sound/decay/keller/dk_idle3.wav
sound/decay/keller/dk_idle4.wav
sound/decay/keller/dk_iknowyouare.wav
sound/decay/keller/dk_kellerfrog.wav
sound/decay/keller/dk_leads0.wav
sound/decay/keller/dk_leads1.wav
sound/decay/keller/dk_leads2.wav
sound/decay/keller/dk_newstuff.wav
sound/decay/keller/dk_ok0.wav
sound/decay/keller/dk_ok1.wav
sound/decay/keller/dk_ok2.wav
sound/decay/keller/dk_pain1.wav
sound/decay/keller/dk_pain2.wav
sound/decay/keller/dk_pain3.wav
sound/decay/keller/dk_pain4.wav
sound/decay/keller/dk_pain5.wav
sound/decay/keller/dk_pain6.wav
sound/decay/keller/dk_pain7.wav
sound/decay/keller/dk_plfear0.wav
sound/decay/keller/dk_plfear1.wav
sound/decay/keller/dk_plfear2.wav
sound/decay/keller/dk_plfear3.wav
sound/decay/keller/dk_rugurinate.wav
sound/decay/keller/dk_scared0.wav
sound/decay/keller/dk_scared1.wav
sound/decay/keller/dk_scared2.wav
sound/decay/keller/dk_screwyou.wav
sound/decay/keller/dk_stare0.wav
sound/decay/keller/dk_stare1.wav
sound/decay/keller/dk_stare2.wav
sound/decay/keller/dk_stop0.wav
sound/decay/keller/dk_stop1.wav
sound/decay/keller/dk_stop2.wav
sound/decay/keller/dk_wait0.wav
sound/decay/keller/dk_wait1.wav
sound/decay/keller/dk_wait2.wav
sound/decay/keller/dk_wait3.wav
sound/decay/rosenberg/ro_01_admin.wav
sound/decay/rosenberg/ro_01_alive.wav
sound/decay/rosenberg/ro_01_assure.wav
sound/decay/rosenberg/ro_01_callhelp.wav
sound/decay/rosenberg/ro_01_chargers.wav
sound/decay/rosenberg/ro_01_dampen.wav
sound/decay/rosenberg/ro_01_danger.wav
sound/decay/rosenberg/ro_01_fields.wav
sound/decay/rosenberg/ro_01_grudge.wav
sound/decay/rosenberg/ro_01_keller.wav
sound/decay/rosenberg/ro_01_leaving.wav
sound/decay/rosenberg/ro_01_letsgo.wav
sound/decay/rosenberg/ro_01_realize.wav
sound/decay/rosenberg/ro_01_sigh.wav
sound/decay/rosenberg/ro_01_spectrom.wav
sound/decay/rosenberg/ro_01_survived.wav
sound/decay/rosenberg/ro_01_touch.wav
sound/decay/rosenberg/ro_01_yesright.wav
sound/decay/rosenberg/ro_02_careful.wav
sound/decay/rosenberg/ro_02_despite.wav
sound/decay/rosenberg/ro_02_elevator.wav
sound/decay/rosenberg/ro_02_follow.wav
sound/decay/rosenberg/ro_02_madeit.wav
sound/decay/rosenberg/ro_02_moving.wav
sound/decay/rosenberg/ro_02_opendoor.wav
sound/decay/rosenberg/ro_02_thanks.wav
sound/decay/rosenberg/ro_02_waithere.wav
sound/decay/rosenberg/ro_03_aligned.wav
sound/decay/rosenberg/ro_03_excellent.wav
sound/decay/rosenberg/ro_03_inside.wav
sound/decay/rosenberg/ro_03_keller.wav
sound/decay/rosenberg/ro_03_madeit.wav
sound/decay/rosenberg/ro_03_makeway.wav
sound/decay/rosenberg/ro_03_notalign.wav
sound/decay/rosenberg/ro_03_notalign2.wav
sound/decay/rosenberg/ro_03_perfect.wav
sound/decay/rosenberg/ro_03_rotated.wav
sound/decay/rosenberg/ro_03_senddown.wav
sound/decay/rosenberg/ro_03_surface.wav
sound/decay/rosenberg/ro_03_toofar.wav
sound/decay/rosenberg/ro_03_waithere.wav
sound/decay/rosenberg/ro_calhoun2.wav
sound/decay/rosenberg/ro_rug.wav
sound/decay/scientist/d01_sci01_waiting.wav
sound/decay/scientist/d01_sci02_door.wav
sound/decay/scientist/d01_sci03_reregister.wav
sound/decay/scientist/d01_sci04_oneatatime.wav
sound/decay/scientist/d01_sci05_bestillcross.wav
sound/decay/scientist/d01_sci06_dontmovegreen.wav
sound/decay/scientist/d01_sci07_spectrometer.wav
sound/decay/scientist/d01_sci08_pushsample.wav
sound/decay/scientist/d01_sci09_pushsample2.wav
sound/decay/scientist/d01_sci10_interesting.wav
sound/decay/scientist/d01_sci11_shouldnthappen.wav
sound/decay/scientist/d01_sci12_impossible.wav
sound/decay/scientist/d01_sci13_jammed.wav
sound/decay/scientist/d01_sci14_right.wav
sound/decay/scientist/d01_sci15_onschedule.wav
sound/decay/scientist/d01_sci16_standby.wav
sound/decay/scientist/d01_sci17_secondary.wav
sound/decay/scientist/d01_sci18_wontshutdown.wav
sound/decay/scientist/d06_sci01_lambdalabs.wav
sound/decay/scientist/d06_sci02_contact.wav
sound/decay/scientist/d06_sci05_launch.wav
sound/decay/scientist/d06_sci07_worktodo.wav
sound/decay/scientist/d06_sci10_emergencyshutdown.wav
sound/decay/scientist/d06_sci11_allclear.wav
sound/decay/scientist/d08_sci01_idnumber.wav
sound/decay/scientist/d08_sci02_scientists.wav
sound/decay/scientist/d08_sci03_destroytrackers.wav
sound/decay/scientist/d08_sci04_ceilinghatch.wav
sound/decay/scientist/d08_sci05_osprey.wav
sound/decay/scientist/ot01_nametag.wav
sound/decay/scientist/ot02_nicergraphics.wav
sound/decay/scientist/ot03_lookatme.wav
sound/decay/scientist/ot04_eyesclosed.wav
sound/decay/scientist/ot05_toilet1.wav
sound/decay/scientist/ot06_gorman1.wav
sound/decay/scientist/ot07_gorman2.wav
sound/decay/scientist/ot08_resetthestage.wav
sound/decay/scientist/ot09_toilet2.wav
sound/decay/scientist/ot10_buttons.wav
sound/decay/scientist/ot11_buttons2.wav
sound/decay/scientist/ot12_gorman3.wav
sound/decay/scientist/ot13_headcrab.wav
sound/decay/scientist/ot14_toilet3.wav
sound/decay/scientist/ot15_gorman4.wav
sound/decay/scientist/ot16_typecasting.wav
sound/decay/scientist/ot17_particleguy.wav
sound/decay/scientist/tr_sci1_sensors.wav
sound/decay/scientist/tr_sci2_veryinteresting.wav
sound/decay/scientist/tr_sci3_welcome.wav
sound/decay/scientist/tr_sci4_legal.wav
sound/decay/scientist/tr_sci5_questions.wav
sound/decay/scientist/tr_sci6_holograph.wav
sound/decay/wheelchair/wheelchair_jog.wav
sound/decay/wheelchair/wheelchair_run.wav
sound/decay/wheelchair/wheelchair_walk.wav
sprites/alien/weapon_slave.txt
