gfx/env/siv2bk.tga
gfx/env/siv2dn.tga
gfx/env/siv2ft.tga
gfx/env/siv2lf.tga
gfx/env/siv2rt.tga
gfx/env/siv2up.tga
maps/fy_desert_night.res
maps/fy_desert_night.txt
models/fy_desert/bush1.mdl
models/fy_desert/bush2.mdl
models/fy_desert/car.mdl
models/fy_desert/grass.mdl
models/fy_desert/shade.mdl
models/fy_desert/tree.mdl
overviews/fy_desert.bmp
overviews/fy_desert.txt
sound/fy_desert/wind.wav 
maps/aim_fuzz.bsp 
