sound/ambience/liftmuzak.wav
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sprites/hl_weapons/weapon_hl357.txt
models/player/airborne01_hr/airborne01_hr.bmp
models/player/airborne01_hr/airborne01_hr.mdl
models/player/airborne01_hr/credit.txt
models/player/airborne01_hs/airborne01_hs.bmp
models/player/airborne01_hs/airborne01_hs.mdl
models/player/airborne01_hs/credit.txt
models/player/airborne01_m/airborne01_m.bmp
models/player/airborne01_m/airborne01_m.mdl
models/player/airborne01_m/credit.txt
models/player/airborne01_r/airborne01_r.bmp
models/player/airborne01_r/airborne01_r.mdl
models/player/airborne01_r/credit.txt
models/player/airborne01_s/airborne01_s.bmp
models/player/airborne01_s/airborne01_s.mdl
models/player/airborne01_s/credit.txt
models/player/airborne02/airborne02.bmp
models/player/airborne02/airborne02.mdl
models/player/airborne02/credit.txt
models/player/airborne02_h/airborne02_h.bmp
models/player/airborne02_h/airborne02_h.mdl
