sound/ambience/liftmuzak.wav
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sprites/hl_weapons/weapon_hl357.txt
models/cubemath/arrow2d.mdl
models/player/40k_BR_AT/40k_BR_AT.mdl
models/player/40k_BR_DV/40k_BR_DV.bmp
models/player/40k_BR_DV/40k_BR_DV.mdl
models/player/40k_BR_TC/40k_BR_TC.bmp
models/player/40k_BR_TC/40k_BR_TC.mdl
models/player/40k_Cadia_Man/40k_Cadia_Man.bmp
models/player/40k_Cadia_Man/40k_Cadia_Man.mdl
models/player/40k_IF_AT/40k_IF_AT.bmp
models/player/40k_IF_AT/40k_IF_AT.mdl
models/player/40k_IF_DV/40k_IF_DV.bmp
models/player/40k_IF_DV/40k_IF_DV.mdl
models/player/40k_IF_TC/40k_IF_TC.bmp
models/player/40k_IF_TC/40k_IF_TC.mdl
models/player/40k_Sentinel/40k_Sentinel.bmp
models/player/40k_Sentinel/40k_Sentinel.mdl
models/player/40k_Sisters_Tenshi/40k_Sisters_Tenshi.bmp
models/player/40k_Sisters_Tenshi/40k_Sisters_Tenshi.mdl
models/player/40k_SM_AT/40k_SM_AT.bmp
models/player/40k_SM_AT/40k_SM_AT.mdl
models/player/40k_SM_DV/40k_SM_DV.bmp
