sprites/hl_weapons/weapon_hl357.txt
models/player/cod_makarov1/cod_makarov1.mdl
models/player/cod_makarov2/cod_makarov2.bmp
models/player/cod_makarov2/cod_makarov2.mdl
models/player/cod_makarov3/cod_makarov3.bmp
models/player/cod_makarov3/cod_makarov3.mdl
models/player/cod_makarov4/cod_makarov4.bmp
models/player/cod_makarov4/cod_makarov4.mdl
models/player/cod_police1/cod_police1.bmp
models/player/cod_police1/cod_police1.mdl
models/player/cod_police2/cod_police2.bmp
models/player/cod_police2/cod_police2.mdl
models/player/cod_police3/cod_police3.bmp
models/player/cod_police3/cod_police3.mdl
models/player/cod_police4/cod_police4.bmp
models/player/cod_police4/cod_police4.mdl
models/player/cod_ranger1/cod_ranger1.bmp
models/player/cod_ranger1/cod_ranger1.mdl
models/player/cod_ranger2/cod_ranger2.bmp
models/player/cod_ranger2/cod_ranger2.mdl
models/player/cod_ranger3/cod_ranger3.bmp
