sprites/hl_weapons/weapon_hl357.txt
models/player/cap_OP4_Shotgun/cap_OP4_Shotgun.bmp
models/player/cap_OP4_Shotgun/cap_OP4_Shotgun.mdl
models/player/cap_OP4_Tower/cap_OP4_Tower.bmp
models/player/cap_OP4_Tower/cap_OP4_Tower.mdl
models/player/cap_OP4_Walter/cap_OP4_Walter.bmp
models/player/cap_OP4_Walter/cap_OP4_Walter.mdl
models/player/cap_otis/cap_otis.bmp
models/player/cap_otis/cap_otis.mdl
models/player/carter/carter.bmp
models/player/carter/carter.mdl
models/player/carter_bm/carter_bm.bmp
models/player/carter_bm/carter_bm.mdl
models/player/chavo/Chavo.bmp
models/player/chavo/Chavo.mdl
models/player/cheems/cheems.bmp
models/player/cheems/cheems.mdl
models/player/chibi_wattson/Chibi_Wattson.bmp
models/player/chibi_wattson/Chibi_Wattson.mdl
models/player/chinamario/chinamario.bmp
models/player/chinamario/chinamario.mdl
