sprites/hl_weapons/weapon_hl357.txt

models/player/cod_ranger3/cod_ranger3.mdl
models/player/cod_ranger4/cod_ranger4.bmp
models/player/cod_ranger4/cod_ranger4.mdl
models/player/cod_rus-force1/cod_rus-force1.bmp
models/player/cod_rus-force1/cod_rus-force1.mdl
models/player/cod_rus-force2/cod_rus-force2.bmp
models/player/cod_rus-force2/cod_rus-force2.mdl
models/player/cod_rus-force3/cod_rus-force3.bmp
models/player/cod_rus-force3/cod_rus-force3.mdl
models/player/cod_rus-force4/cod_rus-force4.bmp
models/player/cod_rus-force4/cod_rus-force4.mdl
models/player/cod_seal1/cod_seal1.bmp
models/player/cod_seal1/cod_seal1.mdl
models/player/cod_seal2/cod_seal2.bmp
models/player/cod_seal2/cod_seal2.mdl
models/player/cod_seal3/cod_seal3.bmp
models/player/cod_seal3/cod_seal3.mdl
models/player/cod_seal4/cod_seal4.bmp
models/player/cod_seal4/cod_seal4.mdl
models/player/cod_shield1/cod_shield1.bmp
