sprites/hl_weapons/weapon_hl357.txt
models/player/40k_SM_DV/40k_SM_DV.mdl
models/player/40k_SM_TC/40k_SM_TC.bmp
models/player/40k_SM_TC/40k_SM_TC.mdl
models/player/40k_UM_AT/40k_UM_AT.bmp
models/player/40k_UM_AT/40k_UM_AT.mdl
models/player/40k_UM_DV/40k_UM_DV.bmp
models/player/40k_UM_DV/40k_UM_DV.mdl
models/player/40k_UM_TC/40k_UM_TC.bmp
models/player/40k_UM_TC/40k_UM_TC.mdl
models/player/ab_dorothy/AB_Dorothy.bmp
models/player/ab_dorothy/AB_Dorothy.mdl
models/player/ab_kratos/AB_Kratos.bmp
models/player/ab_kratos/AB_Kratos.mdl
models/player/ab_rin_shibuya/AB_Rin_Shibuya.bmp
models/player/ab_rin_shibuya/AB_Rin_Shibuya.mdl
models/player/ab_sakura_kinomoto/AB_Sakura_Kinomoto.bmp
models/player/ab_sakura_kinomoto/AB_Sakura_Kinomoto.mdl
models/player/AB_Sr_Pelo_angry/AB_Sr_Pelo_angry.bmp
models/player/AB_Sr_Pelo_angry/AB_Sr_Pelo_angry.mdl
models/player/AB_Sr_Pelo_smiling/AB_Sr_Pelo_smiling.bmp
