sprites/hl_weapons/weapon_hl357.txt

models/player/cap_BS_Unarmored_1/cap_BS_Unarmored_1.bmp
models/player/cap_BS_Unarmored_1/cap_BS_Unarmored_1.mdl
models/player/cap_BS_Unarmored_2/cap_BS_Unarmored_2.bmp
models/player/cap_BS_Unarmored_2/cap_BS_Unarmored_2.mdl
models/player/cap_HL_Construction/cap_HL_Construction.bmp
models/player/cap_HL_Construction/cap_HL_Construction.mdl
models/player/cap_HL_Construction_2/cap_HL_Construction_2.bmp
models/player/cap_HL_Construction_2/cap_HL_Construction_2.mdl
models/player/cap_HL_Gus/cap_HL_Gus.bmp
models/player/cap_HL_Gus/cap_HL_Gus.mdl
models/player/cap_kate/cap_kate.bmp
models/player/cap_kate/cap_kate.mdl
models/player/cap_OP4_Cigar/cap_OP4_Cigar.bmp
models/player/cap_OP4_Cigar/cap_OP4_Cigar.mdl
models/player/cap_OP4_Grunt/cap_OP4_Grunt.bmp
models/player/cap_OP4_Grunt/cap_OP4_Grunt.mdl
models/player/cap_OP4_Recon/cap_OP4_Recon.bmp
models/player/cap_OP4_Recon/cap_OP4_Recon.mdl
models/player/cap_OP4_Shephard/cap_OP4_Shephard.bmp
models/player/cap_OP4_Shephard/cap_OP4_Shephard.mdl
