// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

loz.wad
models/player/young_link1_sc5/young_link1_sc5.bmp
models/player/young_link1_sc5/young_link1_sc5.mdl
models/zelda/characters/Young_Link_equip0_B.mdl
models/zelda/characters/Young_Link_equip0_G.mdl
models/zelda/characters/Young_Link_equip0_P.mdl
models/zelda/characters/Young_Link_equip0_R.mdl
models/zelda/characters/kokiri_boy.mdl
models/zelda/characters/kokiri_girl.mdl
models/zelda/characters/mido.mdl
models/zelda/characters/navi.mdl
models/zelda/characters/saria.mdl
models/zelda/characters/shopkeeper.mdl
models/zelda/enemies/baba.mdl
models/zelda/enemies/baba_root.mdl
models/zelda/enemies/jumper.mdl
models/zelda/enemies/scrub.mdl
models/zelda/enemies/scrub_root.mdl
models/zelda/enemies/wolfos.mdl
models/zelda/items/arrow.mdl
models/zelda/items/heart.mdl
models/zelda/items/heartT.mdl
models/zelda/items/nut.mdl
models/zelda/items/rupee.mdl
models/zelda/items/seeds.mdl
models/zelda/items/shield.mdl
models/zelda/items/stick.mdl
models/zelda/props/gossip.mdl
models/zelda/props/kokiri/dekutree.mdl
models/zelda/props/kokiri/house1.mdl
models/zelda/props/kokiri/house2.mdl
models/zelda/props/kokiri/house3.mdl
models/zelda/props/kokiri/house4.mdl
models/zelda/props/kokiri/house5.mdl
models/zelda/props/kokiri/house6.mdl
models/zelda/props/leaf.mdl
models/zelda/props/leaf2.mdl
models/zelda/props/plant.mdl
models/zelda/props/plant2.mdl
models/zelda/props/pot.mdl
models/zelda/props/pot_gib.mdl
models/zelda/props/rock.mdl
models/zelda/props/rockgibs.mdl
models/zelda/props/statue.mdl
models/zelda/weapons/p_satchel.mdl
models/zelda/weapons/p_satchel_radio.mdl
models/zelda/weapons/p_sling.mdl
models/zelda/weapons/p_stick.mdl
models/zelda/weapons/p_sword.mdl
models/zelda/weapons/seed.mdl
models/zelda/weapons/v_satchel.mdl
models/zelda/weapons/v_satchel_radio.mdl
models/zelda/weapons/v_sling.mdl
models/zelda/weapons/v_stick.mdl
models/zelda/weapons/v_sword.mdl
models/zelda/weapons/w_satchel.mdl
models/zelda/weapons/w_sling.mdl
models/zelda/weapons/w_stick.mdl
models/zelda/weapons/w_sword.mdl
sound/zelda/bonk.wav
sound/zelda/cursor.wav
sound/zelda/enemies/baba_bite.wav
sound/zelda/enemies/baba_die.wav
sound/zelda/enemies/baba_grow.wav
sound/zelda/enemies/hit.wav
sound/zelda/enemies/larva_alert.wav
sound/zelda/enemies/larva_attack.wav
sound/zelda/enemies/larva_die.wav
sound/zelda/enemies/larva_pain.wav
sound/zelda/enemies/pain.wav
sound/zelda/enemies/scrub_attack.wav
sound/zelda/enemies/scrub_crumble.wav
sound/zelda/enemies/scrub_die.wav
sound/zelda/enemies/scrub_down.wav
sound/zelda/enemies/scrub_pain.wav
sound/zelda/enemies/scrub_step.wav
sound/zelda/enemies/scrub_up.wav
sound/zelda/enemies/wolfos_alert.wav
sound/zelda/enemies/wolfos_die.wav
sound/zelda/enemies/wolfos_idle.wav
sound/zelda/enemies/wolfos_pain.wav
sound/zelda/enemies/wolfos_slash.wav
sound/zelda/enemies/wolfos_step.wav
sound/zelda/error.wav
sound/zelda/flutter.wav
sound/zelda/hello.wav
sound/zelda/hey.wav
sound/zelda/link/bigfall.wav
sound/zelda/link/climb.wav
sound/zelda/link/die.wav
sound/zelda/link/fall2.wav
sound/zelda/link/fall3.wav
sound/zelda/link/pain2.wav
sound/zelda/link/pain3.wav
sound/zelda/link/pain4.wav
sound/zelda/link/pain5.wav
sound/zelda/link/swim1.wav
sound/zelda/link/swim2.wav
sound/zelda/link/swim3.wav
sound/zelda/link/yawn.wav
sound/zelda/music/Deku_Tree.mp3
sound/zelda/music/Inside_DT.mp3
sound/zelda/music/Kokiri_Forest.mp3
sound/zelda/music/Kokiri_Forest_start.mp3
sound/zelda/music/battle.wav
sound/zelda/music/fairy.mp3
sound/zelda/music/fountain.mp3
sound/zelda/music/gameover_once.mp3
sound/zelda/music/house.mp3
sound/zelda/music/lostwoods.mp3
sound/zelda/music/shop.mp3
sound/zelda/navi.wav
sound/zelda/save.wav
sound/zelda/save2.wav
sound/zelda/treasure.wav
sound/zelda/weapons/clang.wav
sound/zelda/weapons/miss1.wav
sound/zelda/weapons/miss2.wav
sound/zelda/weapons/spin.wav
sound/zelda/weapons/stick_attack.wav
sound/zelda/weapons/stick_attack2.wav
sound/zelda/weapons/stick_miss.wav
sound/zelda/world/Chest.wav
sound/zelda/world/Item.wav
sound/zelda/world/ammo.wav
sound/zelda/world/block_move.wav
sound/zelda/world/boulder.wav
sound/zelda/world/clunk.wav
sound/zelda/world/door1_close.wav
sound/zelda/world/fairy_get.wav
sound/zelda/world/gossip_laugh.wav
sound/zelda/world/heart.wav
sound/zelda/world/land.wav
sound/zelda/world/mouth.wav
sound/zelda/world/new_item.wav
sound/zelda/world/pickup.wav
sound/zelda/world/plant.wav
sound/zelda/world/potbreak.wav
sound/zelda/world/rock.wav
sound/zelda/world/rupee.wav
sound/zelda/world/rupee_change.wav
sound/zelda/world/secret.wav
sound/zelda/world/stone_move.wav
sound/zelda/world/water1.wav
sprites/zelda/fairy.spr
sprites/zelda/navi.spr
