// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

loz.wad
models/player/young_link2_sc5/young_link2_sc5.bmp
models/player/young_link2_sc5/young_link2_sc5.mdl
models/zelda/characters/navi.mdl
models/zelda/enemies/baba.mdl
models/zelda/enemies/baba2.mdl
models/zelda/enemies/baba_root.mdl
models/zelda/enemies/egg.mdl
models/zelda/enemies/gohma.mdl
models/zelda/enemies/jumper.mdl
models/zelda/enemies/scrub.mdl
models/zelda/enemies/scrub_root.mdl
models/zelda/enemies/spider.mdl
models/zelda/enemies/spider_gold.mdl
models/zelda/enemies/spider_small.mdl
models/zelda/items/heart.mdl
models/zelda/items/heart_big.mdl
models/zelda/items/heartT.mdl
models/zelda/items/rupee.mdl
models/zelda/items/seeds.mdl
models/zelda/items/token.mdl
models/zelda/props/leaf2.mdl
models/zelda/props/plant.mdl
models/zelda/props/warp.mdl
models/zelda/props/warp2.mdl
models/zelda/weapons/p_satchel.mdl
models/zelda/weapons/p_satchel_radio.mdl
models/zelda/weapons/p_sling.mdl
models/zelda/weapons/p_stick.mdl
models/zelda/weapons/p_sword.mdl
models/zelda/weapons/seed.mdl
models/zelda/weapons/v_satchel.mdl
models/zelda/weapons/v_satchel_radio.mdl
models/zelda/weapons/v_sling.mdl
models/zelda/weapons/v_stick.mdl
models/zelda/weapons/v_sword.mdl
models/zelda/weapons/w_satchel.mdl
models/zelda/weapons/w_sling.mdl
models/zelda/weapons/w_stick.mdl
models/zelda/weapons/w_sword.mdl
sound/zelda/enemies/baba_attack.wav
sound/zelda/enemies/baba_bite.wav
sound/zelda/enemies/baba_die.wav
sound/zelda/enemies/baba_grow.wav
sound/zelda/enemies/baba_strike1.wav
sound/zelda/enemies/baba_strike2.wav
sound/zelda/enemies/baba_strike3.wav
sound/zelda/enemies/gohma_alert.wav
sound/zelda/enemies/gohma_attack.wav
sound/zelda/enemies/gohma_birth.wav
sound/zelda/enemies/gohma_crawl.wav
sound/zelda/enemies/gohma_die.wav
sound/zelda/enemies/gohma_idle.wav
sound/zelda/enemies/gohma_intro.wav
sound/zelda/enemies/gohma_pain.wav
sound/zelda/enemies/hit.wav
sound/zelda/enemies/larva_alert.wav
sound/zelda/enemies/larva_attack.wav
sound/zelda/enemies/larva_die.wav
sound/zelda/enemies/larva_pain.wav
sound/zelda/enemies/pain.wav
sound/zelda/enemies/scrub_attack.wav
sound/zelda/enemies/scrub_crumble.wav
sound/zelda/enemies/scrub_die.wav
sound/zelda/enemies/scrub_down.wav
sound/zelda/enemies/scrub_pain.wav
sound/zelda/enemies/scrub_step.wav
sound/zelda/enemies/scrub_up.wav
sound/zelda/enemies/skulltula_alert.wav
sound/zelda/enemies/skulltula_attack.wav
sound/zelda/enemies/skulltula_climb.wav
sound/zelda/enemies/skulltula_die.wav
sound/zelda/enemies/skulltula_drop.wav
sound/zelda/enemies/skulltula_idle.wav
sound/zelda/enemies/skulltula_lunge.wav
sound/zelda/enemies/skulltula_move.wav
sound/zelda/enemies/skulltula_move2.wav
sound/zelda/error.wav
sound/zelda/fanfare_small.wav
sound/zelda/hey.wav
sound/zelda/link/bigfall.wav
sound/zelda/link/climb.wav
sound/zelda/link/die.wav
sound/zelda/link/fall1.wav
sound/zelda/link/fall2.wav
sound/zelda/link/fall3.wav
sound/zelda/link/pain2.wav
sound/zelda/link/pain3.wav
sound/zelda/link/pain4.wav
sound/zelda/link/pain5.wav
sound/zelda/link/swim1.wav
sound/zelda/link/swim2.wav
sound/zelda/link/swim3.wav
sound/zelda/link/yawn.wav
sound/zelda/listen.wav
sound/zelda/look.wav
sound/zelda/music/Inside_DT.mp3
sound/zelda/music/battle.wav
sound/zelda/music/boss.mp3
sound/zelda/music/boss_clear.mp3
sound/zelda/music/boss_intro.mp3
sound/zelda/music/gameover_once.mp3
sound/zelda/music/heart_container.mp3
sound/zelda/save.wav
sound/zelda/save2.wav
sound/zelda/token.wav
sound/zelda/treasure.wav
sound/zelda/watchout.wav
sound/zelda/weapons/clang.wav
sound/zelda/weapons/miss1.wav
sound/zelda/weapons/miss2.wav
sound/zelda/weapons/spin.wav
sound/zelda/weapons/stick_attack.wav
sound/zelda/weapons/stick_attack2.wav
sound/zelda/weapons/stick_miss.wav
sound/zelda/world/Chest.wav
sound/zelda/world/Item.wav
sound/zelda/world/ammo.wav
sound/zelda/world/block_move.wav
sound/zelda/world/block_stop.wav
sound/zelda/world/boss_door.wav
sound/zelda/world/boss_glow.wav
sound/zelda/world/boss_warp.wav
sound/zelda/world/boulder.wav
sound/zelda/world/chest_appear.wav
sound/zelda/world/chime.wav
sound/zelda/world/clunk.wav
sound/zelda/world/door1_close.wav
sound/zelda/world/door1_open.wav
sound/zelda/world/dt_log.wav
sound/zelda/world/fire.wav
sound/zelda/world/flame.wav
sound/zelda/world/heart.wav
sound/zelda/world/ignite.wav
sound/zelda/world/ladder.wav
sound/zelda/world/land.wav
sound/zelda/world/pickup.wav
sound/zelda/world/plant.wav
sound/zelda/world/potbreak.wav
sound/zelda/world/rock.wav
sound/zelda/world/rupee.wav
sound/zelda/world/rupee_change.wav
sound/zelda/world/secret.wav
sound/zelda/world/shake.wav
sound/zelda/world/stone_move.wav
sound/zelda/world/switch.wav
sprites/zelda/fairy.spr
sprites/zelda/fire_z.spr
sprites/zelda/sparkle.spr
sprites/zelda/xssmke1_z.spr
