1
models/player/robof/robof.mdl
models/player/cj_gta/player.mdl
models/player/cj_gta/playerT.mdl
models/player/cj_HDsuit/cj_HDsuit.mdl
models/player/cj_TCsuit/cj_TCsuit.mdl
models/player/cj_UDsuit/cj_UDsuit.mdl

2
models/player/Scorpion/Scorpion.mdl
models/player/Scorpion/Scorpion.bmp
models/player/Sonic_Forces_Classic_c/Sonic_Forces_Classic_c.mdl
models/player/Sonic_Forces_Classic_c/Sonic_Forces_Classic_c.bmp
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.mdl
models/player/Sonic_Forces_Classic/Sonic_Forces_Classic.bmp
sound/player/playersounds/tails/drop1.wav
sound/player/playersounds/tails/longjump2.wav
sound/player/playersounds/tails/newjump.wav

3
models/player/sci_wheelchair/sci_wheelchair.mdl
models/player/sci_wheelchair/sci_wheelchair.bmp
models/player/security_wheelchair/security_wheelchair.mdl
models/player/security_wheelchair/security_wheelchair.bmp
models/player/soldier_wheelchair/soldier_wheelchair.mdl
models/player/soldier_wheelchair/soldier_wheelchair.bmp

4
models/player/LOZ_Link/LOZ_Link.mdl
models/player/LOZ_LinkC/LOZ_LinkC.mdl
models/player/UGG_Goose/UGG_Goose.mdl
models/player/UGG_Goose/UGG_Goose.bmp
models/player/UGG_GooseC/UGG_GooseC.mdl
models/player/UGG_GooseC/UGG_Goose.bmp
sound/player/playersounds/goose/honk.wav
sound/player/playersounds/goose/honk2.wav

5
models/player/scientist_mad_01/scientist_mad_01.mdl
models/player/scientist_mad_01/scientist_mad_01.bmp
models/player/Teemo/Teemo.mdl
models/player/Teemo/Teemo.bmp
sound/player/playersounds/teemo_hut.wav
models/player/Aviator_Crash/Aviator_Crash.bmp
models/player/Aviator_Crash/Aviator_Crash.mdl
models/player/Biker_Crash/Biker_Crash.bmp
models/player/Biker_Crash/Biker_Crash.mdl
models/player/Crash_Alt/Crash_Alt.bmp
models/player/Crash_Alt/Crash_Alt.mdl
models/player/Crash_Bandicoot/Crash_Bandicoot.bmp
models/player/Crash_Bandicoot/Crash_Bandicoot.mdl
models/player/Crash_Color/Crash_Color.bmp
models/player/Crash_Color/Crash_Color.mdl
models/player/Fake_Crash/Fake_Crash.bmp
models/player/Fake_Crash/Fake_Crash.mdl
models/player/Jetpack_Crash/Jetpack_Crash.bmp
models/player/Jetpack_Crash/Jetpack_Crash.mdl
models/player/Scuba_Crash/Scuba_Crash.bmp
models/player/Scuba_Crash/Scuba_Crash.mdl
sound/player/playersounds/crash_bandicoot/crash/jump.wav
sound/player/playersounds/crash_bandicoot/crash/woah.wav
sound/player/playersounds/crash_bandicoot/fakecrash/ouch.wav

6
models/player/Pitusas/Pitusas.bmp
models/player/Pitusas/Pitusas.mdl
models/player/Pitusas_HQ/Pitusas_HQ.mdl
models/player/Pitusas_HQ/pitusas_HQ.bmp
models/player/trump/trump.mdl	
models/player/MP_Toad/MP_Toad.bmp
models/player/MP_Toad/MP_Toad.mdl
models/player/MP_ToadC/MP_ToadC.bmp
models/player/MP_ToadC/MP_ToadC.mdl
sound/player/playersounds/toad/big_attack.wav
sound/player/playersounds/toad/death.wav
sound/player/playersounds/toad/death2.wav
sound/player/playersounds/toad/grenade.wav
sound/player/playersounds/toad/jump.wav
sound/player/playersounds/toad/long_jump.wav
sound/player/playersounds/toad/melee_attack.wav

7
models/player/sa_bigsmoke/sa_bigsmoke.bmp
models/player/sa_bigsmoke/sa_bigsmoke.mdl
models/player/sa_cesar/sa_cesar.bmp
models/player/sa_cesar/sa_cesar.mdl
models/player/sa_cj/sa_cj.bmp
models/player/sa_cj/sa_cj.mdl
models/player/sa_kendl/sa_kendl.bmp
models/player/sa_kendl/sa_kendl.mdl
models/player/sa_ogloc/sa_ogloc.bmp
models/player/sa_ogloc/sa_ogloc.mdl
models/player/sa_ryder/sa_ryder.bmp
models/player/sa_ryder/sa_ryder.mdl
models/player/sa_smokevest/sa_smokevest.bmp
models/player/sa_smokevest/sa_smokevest.mdl
models/player/sa_sweet/sa_sweet.bmp
models/player/sa_sweet/sa_sweet.mdl

8
models/player/gang_ballas1/gang_ballas1.bmp
models/player/gang_ballas1/gang_ballas1.mdl
models/player/gang_ballas2/gang_ballas2.bmp
models/player/gang_ballas2/gang_ballas2.mdl
models/player/gang_ballas3/gang_ballas3.bmp
models/player/gang_ballas3/gang_ballas3.mdl
models/player/gang_fam1/gang_fam1.bmp
models/player/gang_fam1/gang_fam1.mdl
models/player/gang_fam2/gang_fam2.bmp
models/player/gang_fam2/gang_fam2.mdl
models/player/gang_fam3/gang_fam3.bmp
models/player/gang_fam3/gang_fam3.mdl
models/player/gang_lsv1/gang_lsv1.bmp
models/player/gang_lsv1/gang_lsv1.mdl
models/player/gang_lsv2/gang_lsv2.bmp
models/player/gang_lsv2/gang_lsv2.mdl
models/player/gang_lsv3/gang_lsv3.bmp
models/player/gang_lsv3/gang_lsv3.mdl
models/player/gang_sfr1/gang_sfr1.bmp
models/player/gang_sfr1/gang_sfr1.mdl
models/player/gang_sfr2/gang_sfr2.bmp
models/player/gang_sfr2/gang_sfr2.mdl
models/player/gang_sfr3/gang_sfr3.bmp
models/player/gang_sfr3/gang_sfr3.mdl
models/player/gang_vla1/gang_vla1.bmp
models/player/gang_vla1/gang_vla1.mdl
models/player/gang_vla2/gang_vla2.bmp
models/player/gang_vla2/gang_vla2.mdl
models/player/gang_vla3/gang_vla3.bmp
models/player/gang_vla3/gang_vla3.mdl

9
models/player/agente_smith/barney.mdl
models/player/agente_smith/barneyT.mdl
models/player/Scream/Scream.bmp
models/player/Scream/Scream.mdl
models/player/Scream/readme.txt
models/player/SSreichfuhrer/SSreichfuhrer.bmp
models/player/SSreichfuhrer/SSreichfuhrer.mdl
models/player/SSreichfuhrer/Thumbs.db
models/player/naziCap/Thumbs.db
models/player/naziCap/nazicap.bmp
models/player/naziCap/nazicap.mdl
models/player/naziD250/Thumbs.db
models/player/naziD250/naziD250.bmp
models/player/naziD250/naziD250.mdl
models/player/newhitler/newhitler.bmp
models/player/newhitler/newhitler.mdl

10
models/player/Moonman/Moonman.bmp
models/player/Moonman/Moonman.mdl
models/player/duke/duke.bmp
models/player/duke/duke.mdl
models/player/AmongUs_Crewmate/AmongUs_Crewmate.bmp
models/player/AmongUs_Crewmate/AmongUs_Crewmate.mdl
models/player/AmongUs_Crewmate/Credits.txt

11
models/player/TF2_HHH/TF2_HHH.bmp
models/player/TF2_HHH/TF2_HHH.mdl
models/player/chinamario/chinamario.bmp
models/player/chinamario/chinamario.mdl

12
models/player/Bambo_Hecu/Bambo_Hecu.mdl
models/player/Bambo_Hecu/Bambo_hecu.bmp
models/player/Bambo_cammo/Bambo_cammo.bmp
models/player/Bambo_cammo/Bambo_cammo.mdl
models/player/Bambo_tc/Bambo_tc.bmp
models/player/Bambo_tc/Bambo_tc.mdl
models/player/Bambo_winter/Bambo_winter.bmp
models/player/Bambo_winter/Bambo_winter.mdl

13
models/player/pepsiman/pepsiman.bmp
models/player/pepsiman/pepsiman.mdl
models/player/dingdong/dingdong.bmp
models/player/dingdong/dingdong.mdl
models/player/dingdong/readme.txt
models/player/orderly_happily/orderly_happily.bmp
models/player/orderly_happily/orderly_happily.mdl
models/player/orderly_punished/orderly_punished.bmp
models/player/orderly_punished/orderly_punished.mdl

14
models/player/SDM_DiagonalMario/SDM_DiagonalMario.bmp
models/player/SDM_DiagonalMario/SDM_DiagonalMario.mdl
models/player/31Minutos_Juan/31Minutos_Juan.bmp
models/player/31Minutos_Juan/31Minutos_Juan.mdl
models/player/Noita_Witch/Noita_Witch.mdl
models/player/Noita_Witch_C/Noita_Witch_C.mdl

15
models/player/FNV_RiotRanger/FNV_RiotRanger.bmp
models/player/FNV_RiotRanger/FNV_RiotRanger.mdl
models/player/KMD_Lucoa/KMD_Lucoa.bmp
models/player/KMD_Lucoa/KMD_Lucoa.mdl
models/player/KMD_Lucoa_alt/KMD_Lucoa_alt.bmp
models/player/KMD_Lucoa_alt/KMD_Lucoa_alt.mdl

16
models/player/KMD_Lucoa_alt_hatm/KMD_Lucoa_alt_hatm.bmp
models/player/KMD_Lucoa_alt_hatm/KMD_Lucoa_alt_hatm.mdl
models/player/KMD_Lucoa_bikini/KMD_Lucoa_bikini.bmp
models/player/KMD_Lucoa_bikini/KMD_Lucoa_bikini.mdl
models/player/KMD_Lucoa_bikini_hatm/KMD_Lucoa_bikini_hatm.bmp
models/player/KMD_Lucoa_bikini_hatm/KMD_Lucoa_bikini_hatm.mdl

17
models/player/KMD_Lucoa_hatm/KMD_Lucoa_hatm.bmp
models/player/KMD_Lucoa_hatm/KMD_Lucoa_hatm.mdl
models/player/dangeroustoy2/dangeroustoy2.bmp
models/player/dangeroustoy2/dangeroustoy2.mdl
models/player/dangeroustoy3/dangeroustoy3.bmp
models/player/dangeroustoy3/dangeroustoy3.mdl

18
models/player/zita/README.txt
models/player/zita/zita/zita.bmp
models/player/zita/zita/zita.mdl
models/player/conejo/conejo.bmp
models/player/conejo/conejo.mdl
models/player/FNV_T-51B/FNV_T-51B.bmp
models/player/FNV_T-51B/FNV_T-51B.mdl

19
models/player/revenant_doot/README.txt
models/player/revenant_doot/revenant_doot.bmp
models/player/revenant_doot/revenant_doot.mdl
models/player/dio/Readme.txt
models/player/dio/dio.bmp
models/player/dio/dio.mdl
models/player/wendigo/README.txt
models/player/wendigo/wendigo.bmp
models/player/wendigo/wendigo.mdl

20
models/player/haydee/haydee.bmp
models/player/haydee/haydee.mdl
models/player/haydee_black/haydee_black.bmp
models/player/haydee_black/haydee_black.mdl
models/player/haydee_black_hd/haydee_black_hd.bmp
models/player/haydee_black_hd/haydee_black_hd.mdl

21
models/player/haydee_black_low/haydee_black_low.bmp
models/player/haydee_black_low/haydee_black_low.mdl
models/player/haydee_color/haydee_color.bmp
models/player/haydee_color/haydee_color.mdl
models/player/haydee_color_hd/haydee_color_hd.bmp
models/player/haydee_color_hd/haydee_color_hd.mdl

22
models/player/haydee_color_low/haydee_color_low.bmp
models/player/haydee_color_low/haydee_color_low.mdl
models/player/haydee_hd/haydee_hd.bmp
models/player/haydee_hd/haydee_hd.mdl
models/player/haydee_low/haydee_low.bmp
models/player/haydee_low/haydee_low.mdl

23
models/player/Alcatraz/Alcatraz.mdl
models/player/Alcatraz/scrn1.jpg
models/player/Alcatraz/scrn2.jpg
models/player/AB_Woody/AB_Woody.bmp
models/player/AB_Woody/AB_Woody.mdl
models/player/AB_Woody/credits.txt
sound/player/playersounds/ts/dive.wav
models/player/ts_agent/ts_agent.bmp
models/player/ts_agent/ts_agent.mdl

24
models/player/ts_castor/ts_castor.bmp
models/player/ts_castor/ts_castor.mdl
models/player/ts_gordon/ts_gordon.bmp
models/player/ts_gordon/ts_gordon.mdl
models/player/ts_hitman/ts_hitman.bmp
models/player/ts_hitman/ts_hitman.mdl

25
models/player/ts_laurence/ts_laurence.bmp
models/player/ts_laurence/ts_laurence.mdl
models/player/ts_merc/ts_merc.bmp
models/player/ts_merc/ts_merc.mdl
models/player/ts_seal/ts_seal.bmp
models/player/ts_seal/ts_seal.mdl

26
models/player/vectorman/vectorman.bmp
models/player/vectorman/vectorman.mdl
models/player/CH_Cuphead/CH_Cuphead.bmp
models/player/CH_Cuphead/CH_Cuphead.mdl
models/player/CH_Cuphead_C/CH_Cuphead_C.bmp
models/player/CH_Cuphead_C/CH_Cuphead_C.mdl

27
models/player/CH_Mugman/CH_Mugman.bmp
models/player/CH_Mugman/CH_Mugman.mdl
models/player/CH_Mugman_C/CH_Mugman_C.bmp
models/player/CH_Mugman_C/CH_Mugman_C.mdl
models/player/Atlas/Atlas.bmp
models/player/Atlas/Atlas.mdl
models/player/Atlas/Thumbs.db

28
models/player/P-Body/P-Body.bmp
models/player/P-Body/P-Body.mdl
models/player/P-Body/Thumbs.db
models/player/sp_phillip/phillip_credits.txt
models/player/sp_phillip/sp_phillip.bmp
models/player/sp_phillip/sp_phillip.mdl
models/player/sp_terrance/sp_terrance.bmp
models/player/sp_terrance/sp_terrance.mdl
models/player/sp_terrance/terrance_credits.txt

29
models/player/AB_Sr_Pelo_angry/AB_Sr_Pelo_angry.bmp
models/player/AB_Sr_Pelo_angry/AB_Sr_Pelo_angry.mdl
models/player/AB_Sr_Pelo_smiling/AB_Sr_Pelo_smiling.bmp
models/player/AB_Sr_Pelo_smiling/AB_Sr_Pelo_smiling.mdl
sound/player/playersounds/AB_Sr_Pelo_smiling/bernakle1.wav
sound/player/playersounds/AB_Sr_Pelo_smiling/bernakle2.wav
sound/player/playersounds/AB_Sr_Pelo_smiling/boom.wav
sound/player/playersounds/AB_Sr_Pelo_smiling/dead.wav
sound/player/playersounds/AB_Sr_Pelo_smiling/jump.wav
sound/player/playersounds/AB_Sr_Pelo_smiling/tatata.wav
models/player/TBOI_Isaac/TBOI_Isaac.mdl

30
models/player/ZAMN_Guy/ZAMN_Guy.bmp
models/player/ZAMN_Guy/ZAMN_Guy.mdl
models/player/AntiVirus/AntiVirus(Original).bmp
models/player/AntiVirus/AntiVirus.bmp
models/player/AntiVirus/AntiVirus.mdl
models/player/skelepuncher/skelepuncher.bmp
models/player/skelepuncher/skelepuncher.mdl
models/player/skelepuncher/skelepuncher_credits.txt
models/player/skelepuncher_color/skelepuncher_color.bmp
models/player/skelepuncher_color/skelepuncher_color.mdl
models/player/skelepuncher_color/skelepuncher_color_credits.txt

31
models/player/benson/Benson.mdl
models/player/benson/benson.bmp
models/player/cardboard_man/cardboard_man.bmp
models/player/cardboard_man/cardboard_man.mdl
models/player/cl_barney/cl_barney.bmp
models/player/cl_barney/cl_barney.mdl

32
models/player/cl_chav/cl_chav.bmp
models/player/cl_chav/cl_chav.mdl
models/player/cl_gus/cl_gus.bmp
models/player/cl_gus/cl_gus.mdl
models/player/cl_sarge/cl_sarge.bmp
models/player/cl_sarge/cl_sarge.mdl

33
models/player/cl_sci1/cl_sci1.bmp
models/player/cl_sci1/cl_sci1.mdl
models/player/cl_sci2/cl_sci2.bmp
models/player/cl_sci2/cl_sci2.mdl
models/player/cl_sci3/cl_sci3.bmp
models/player/cl_sci3/cl_sci3.mdl

34
models/player/cl_sci4/cl_sci4.bmp
models/player/cl_sci4/cl_sci4.mdl
models/player/payne.bmp
models/player/payne.mdl
models/player/GS_Vector/GS_Vector.bmp
models/player/GS_Vector/GS_Vector.mdl
models/player/GS_Vector/GS_VectorT.mdl
models/player/GS_Vector/GS_Vectorx.mdl
models/player/GS_Vector/Thumbs.db

35
models/player/GS_DSpace_1/GS_DSpace_1.bmp
models/player/GS_DSpace_1/GS_DSpace_1.mdl
models/player/GS_DSpace_1/Thumbs.db
