sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/NVA-amobe1/NVA-amobe1.bmp
models/player/NVA-amobe1/NVA-amobe1.mdl
models/player/NVA-amobe2/2handshoot.smd
models/player/NVA-amobe2/action_retina.smd
models/player/NVA-amobe2/action_studycart.smd
models/player/NVA-amobe2/action_wave.smd
models/player/NVA-amobe2/barnaclechew.smd
models/player/NVA-amobe2/barnaclecrunch.smd
models/player/NVA-amobe2/barnaclehit.smd
models/player/NVA-amobe2/barnaclepull.smd
models/player/NVA-amobe2/body3.smd
models/player/NVA-amobe2/crawl.smd
models/player/NVA-amobe2/crouch_aim_bowscope_blend1.smd
models/player/NVA-amobe2/crouch_aim_bowscope_blend2.smd
models/player/NVA-amobe2/crouch_aim_bow_blend1.smd
models/player/NVA-amobe2/crouch_aim_bow_blend2.smd
models/player/NVA-amobe2/crouch_aim_crowbar_blend1.smd
models/player/NVA-amobe2/crouch_aim_crowbar_blend2.smd
models/player/NVA-amobe2/crouch_aim_egon_blend1.smd
models/player/NVA-amobe2/crouch_aim_egon_blend2.smd
