sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/NVA-amobe2/crouch_draw_saw_blend1.smd
models/player/NVA-amobe2/crouch_draw_saw_blend2.smd
models/player/NVA-amobe2/crouch_draw_shotgun_blend1.smd
models/player/NVA-amobe2/crouch_draw_shotgun_blend2.smd
models/player/NVA-amobe2/crouch_draw_sniper_blend1.smd
models/player/NVA-amobe2/crouch_draw_sniper_blend2.smd
models/player/NVA-amobe2/crouch_draw_squeak_blend1.smd
models/player/NVA-amobe2/crouch_draw_squeak_blend2.smd
models/player/NVA-amobe2/crouch_draw_trip_blend1.smd
models/player/NVA-amobe2/crouch_draw_trip_blend2.smd
models/player/NVA-amobe2/crouch_draw_uzis_blend1.smd
models/player/NVA-amobe2/crouch_draw_uzis_blend2.smd
models/player/NVA-amobe2/crouch_draw_uzis_left_blend1.smd
models/player/NVA-amobe2/crouch_draw_uzis_left_blend2.smd
models/player/NVA-amobe2/crouch_hold_gren_blend1.smd
models/player/NVA-amobe2/crouch_hold_gren_blend2.smd
models/player/NVA-amobe2/crouch_hold_wrench_blend1.smd
models/player/NVA-amobe2/crouch_hold_wrench_blend2.smd
models/player/NVA-amobe2/crouch_idle.smd
models/player/NVA-amobe2/crouch_reload_bow_blend1.smd
