sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/NVA-amobe2/crouch_aim_gauss_blend1.smd
models/player/NVA-amobe2/crouch_aim_gauss_blend2.smd
models/player/NVA-amobe2/crouch_aim_gren_blend1.smd
models/player/NVA-amobe2/crouch_aim_gren_blend2.smd
models/player/NVA-amobe2/crouch_aim_hive_blend1.smd
models/player/NVA-amobe2/crouch_aim_hive_blend2.smd
models/player/NVA-amobe2/crouch_aim_m16_blend1.smd
models/player/NVA-amobe2/crouch_aim_m16_blend2.smd
models/player/NVA-amobe2/crouch_aim_minigun_blend1.smd
models/player/NVA-amobe2/crouch_aim_minigun_blend2.smd
models/player/NVA-amobe2/crouch_aim_mp5_blend1.smd
models/player/NVA-amobe2/crouch_aim_mp5_blend2.smd
models/player/NVA-amobe2/crouch_aim_onehanded_blend1.smd
models/player/NVA-amobe2/crouch_aim_onehanded_blend2.smd
models/player/NVA-amobe2/crouch_aim_python_blend1.smd
models/player/NVA-amobe2/crouch_aim_python_blend2.smd
models/player/NVA-amobe2/crouch_aim_rpg_blend1.smd
models/player/NVA-amobe2/crouch_aim_rpg_blend2.smd
models/player/NVA-amobe2/crouch_aim_saw_blend1.smd
models/player/NVA-amobe2/crouch_aim_saw_blend2.smd
