sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/player/NVA-amobe2/crouch_draw_egon_blend1.smd
models/player/NVA-amobe2/crouch_draw_egon_blend2.smd
models/player/NVA-amobe2/crouch_draw_gauss_blend1.smd
models/player/NVA-amobe2/crouch_draw_gauss_blend2.smd
models/player/NVA-amobe2/crouch_draw_gren_blend1.smd
models/player/NVA-amobe2/crouch_draw_gren_blend2.smd
models/player/NVA-amobe2/crouch_draw_hive_blend1.smd
models/player/NVA-amobe2/crouch_draw_hive_blend2.smd
models/player/NVA-amobe2/crouch_draw_m16_blend1.smd
models/player/NVA-amobe2/crouch_draw_m16_blend2.smd
models/player/NVA-amobe2/crouch_draw_minigun_blend1.smd
models/player/NVA-amobe2/crouch_draw_minigun_blend2.smd
models/player/NVA-amobe2/crouch_draw_mp5_blend1.smd
models/player/NVA-amobe2/crouch_draw_mp5_blend2.smd
models/player/NVA-amobe2/crouch_draw_onehanded_blend1.smd
models/player/NVA-amobe2/crouch_draw_onehanded_blend2.smd
models/player/NVA-amobe2/crouch_draw_python_blend1.smd
models/player/NVA-amobe2/crouch_draw_python_blend2.smd
models/player/NVA-amobe2/crouch_draw_rpg_blend1.smd
models/player/NVA-amobe2/crouch_draw_rpg_blend2.smd
