gfx/env/hackbk.bmp
gfx/env/hackbk.tga
gfx/env/hackdn.bmp
gfx/env/hackdn.tga
gfx/env/hackft.bmp
gfx/env/hackft.tga
gfx/env/hacklf.bmp
gfx/env/hacklf.tga
gfx/env/hackrt.bmp
gfx/env/hackrt.tga
gfx/env/hackup.bmp
gfx/env/hackup.tga
models/player/NVA-amobe2/crouch_shoot_m203_blend2.smd
models/player/NVA-amobe2/crouch_shoot_minigun_blend1.smd
models/player/NVA-amobe2/crouch_shoot_minigun_blend2.smd
models/player/NVA-amobe2/crouch_shoot_mp5_blend1.smd
models/player/NVA-amobe2/crouch_shoot_mp5_blend2.smd
models/player/NVA-amobe2/crouch_shoot_onehanded_blend1.smd
models/player/NVA-amobe2/crouch_shoot_onehanded_blend2.smd
models/player/NVA-amobe2/crouch_shoot_python_blend1.smd
models/player/NVA-amobe2/crouch_shoot_python_blend2.smd
models/player/NVA-amobe2/crouch_shoot_rpg_blend1.smd
models/player/NVA-amobe2/crouch_shoot_rpg_blend2.smd
models/player/NVA-amobe2/crouch_shoot_saw_blend1.smd
models/player/NVA-amobe2/crouch_shoot_saw_blend2.smd
models/player/NVA-amobe2/crouch_shoot_shotgun_blend1.smd
models/player/NVA-amobe2/crouch_shoot_shotgun_blend2.smd
models/player/NVA-amobe2/crouch_shoot_sniperscope_blend1.smd
models/player/NVA-amobe2/crouch_shoot_sniperscope_blend2.smd
models/player/NVA-amobe2/crouch_shoot_sniper_blend1.smd
models/player/NVA-amobe2/crouch_shoot_sniper_blend2.smd
models/player/NVA-amobe2/crouch_shoot_squeak_blend1.smd
