// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/quake1/grenade.mdl
models/quake1/p_axe.mdl
models/quake1/p_grenade.mdl
models/quake1/p_medkit.mdl
models/quake1/p_nailgun.mdl
models/quake1/p_nailgun2.mdl
models/quake1/p_rocket.mdl
models/quake1/p_shotgun.mdl
models/quake1/p_shotgun2.mdl
models/quake1/p_thunder.mdl
models/quake1/rocket.mdl
models/quake1/shotgunshell.mdl
models/quake1/spike.mdl
models/quake1/v_axe.mdl
models/quake1/v_grenade.mdl
models/quake1/v_medkit.mdl
models/quake1/v_nailgun.mdl
models/quake1/v_nailgun2.mdl
models/quake1/v_rocket.mdl
models/quake1/v_shotgun.mdl
models/quake1/v_shotgun2.mdl
models/quake1/v_thunder.mdl
models/quake1/w_armor_g.mdl
models/quake1/w_armor_r.mdl
models/quake1/w_armor_y.mdl
models/quake1/w_axe.mdl
models/quake1/w_backpack.mdl
models/quake1/w_grenade.mdl
models/quake1/w_invis.mdl
models/quake1/w_invul.mdl
models/quake1/w_keycard_gold.mdl
models/quake1/w_keycard_silver.mdl
models/quake1/w_keyrune_gold.mdl
models/quake1/w_keyrune_silver.mdl
models/quake1/w_medkit.mdl
models/quake1/w_megahealth.mdl
models/quake1/w_nailgun.mdl
models/quake1/w_nailgun2.mdl
models/quake1/w_nailgun_ammo.mdl
models/quake1/w_quad.mdl
models/quake1/w_rocket.mdl
models/quake1/w_rocket_ammo.mdl
models/quake1/w_rune1.mdl
models/quake1/w_shotgun.mdl
models/quake1/w_shotgun2.mdl
models/quake1/w_shotgun_ammo.mdl
models/quake1/w_suit.mdl
models/quake1/w_thunder.mdl
models/quake1/w_thunder_ammo.mdl
models/quake1/zombiegib.mdl
q1_gfx.wad
sound/quake1/ammo.wav
sound/quake1/armor.wav
sound/quake1/bkey.wav
sound/quake1/doors/stndr1.wav
sound/quake1/doors/stndr2.wav
sound/quake1/explode.wav
sound/quake1/gib.wav
sound/quake1/health.wav
sound/quake1/itemspawn.wav
sound/quake1/mkey.wav
sound/quake1/monsters/scrag/hit.wav
sound/quake1/monsters/scrag/shoot.wav
sound/quake1/monsters/zombie/hit.wav
sound/quake1/monsters/zombie/miss.wav
sound/quake1/player/burn1.wav
sound/quake1/player/burn2.wav
sound/quake1/player/death1.wav
sound/quake1/player/death2.wav
sound/quake1/player/death3.wav
sound/quake1/player/death4.wav
sound/quake1/player/death5.wav
sound/quake1/player/drown.wav
sound/quake1/player/fall.wav
sound/quake1/player/jump.wav
sound/quake1/player/pain1.wav
sound/quake1/player/pain2.wav
sound/quake1/player/pain3.wav
sound/quake1/player/pain4.wav
sound/quake1/player/pain5.wav
sound/quake1/player/pain6.wav
sound/quake1/player/wpain1.wav
sound/quake1/player/wpain2.wav
sound/quake1/powerups/invis.wav
sound/quake1/powerups/invis_warn.wav
sound/quake1/powerups/invul.wav
sound/quake1/powerups/invul_s.wav
sound/quake1/powerups/invul_warn.wav
sound/quake1/powerups/quad.wav
sound/quake1/powerups/quad_s.wav
sound/quake1/powerups/quad_warn.wav
sound/quake1/powerups/suit.wav
sound/quake1/powerups/suit_warn.wav
sound/quake1/rune.wav
sound/quake1/shock.wav
sound/quake1/tele.wav
sound/quake1/weapon.wav
sound/quake1/weapons/axe.wav
sound/quake1/weapons/axe_hit.wav
sound/quake1/weapons/bounce.wav
sound/quake1/weapons/grenade.wav
sound/quake1/weapons/nailgun1.wav
sound/quake1/weapons/nailgun2.wav
sound/quake1/weapons/rocket.wav
sound/quake1/weapons/shotgun1.wav
sound/quake1/weapons/shotgun2.wav
sound/quake1/weapons/thunder1.wav
sound/quake1/weapons/thunder2.wav
sound/quake1/weapons/tink1.wav
sprites/quake1/crosshairs.spr
sprites/quake1/hudcb.spr
sprites/quake1/hudgl.spr
sprites/quake1/hudglammo.spr
sprites/quake1/hudlg.spr
sprites/quake1/hudlgammo.spr
sprites/quake1/hudng.spr
sprites/quake1/hudngammo.spr
sprites/quake1/hudrl.spr
sprites/quake1/hudrlammo.spr
sprites/quake1/hudsg.spr
sprites/quake1/hudsgammo.spr
sprites/quake1/hudsng.spr
sprites/quake1/hudsngammo.spr
sprites/quake1/hudssg.spr
sprites/quake1/hudssgammo.spr
sprites/quake1/weapons/weapon_qaxe.txt
sprites/quake1/weapons/weapon_qgrenade.txt
sprites/quake1/weapons/weapon_qnailgun.txt
sprites/quake1/weapons/weapon_qnailgun2.txt
sprites/quake1/weapons/weapon_qrocket.txt
sprites/quake1/weapons/weapon_qshotgun.txt
sprites/quake1/weapons/weapon_qshotgun2.txt
sprites/quake1/weapons/weapon_qthunder.txt
