// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/discbk.tga
gfx/env/discdn.tga
gfx/env/discft.tga
gfx/env/disclf.tga
gfx/env/discrt.tga
gfx/env/discup.tga
models/ricochet/disc.mdl
models/ricochet/disc_hard.mdl
models/ricochet/p_disc.mdl
models/ricochet/pow_fast.mdl
models/ricochet/pow_freeze.mdl
models/ricochet/pow_hard.mdl
models/ricochet/pow_triple.mdl
models/ricochet/v_disc.mdl
ricochet.wad
sound/ricochet/dischit.wav
sound/ricochet/discreturn.wav
sound/ricochet/items/gunpickup2.wav
sound/ricochet/powerup.wav
sound/ricochet/pspawn.wav
sound/ricochet/r_tele1.wav
sound/ricochet/scream1.wav
sound/ricochet/scream2.wav
sound/ricochet/scream3.wav
sound/ricochet/triggerjump.wav
sound/ricochet/weapons/altfire.wav
sound/ricochet/weapons/cbar_miss1.wav
sound/ricochet/weapons/rocket1.wav
sound/ricochet/weapons/xbow_hit1.wav
sound/ricochet/weapons/xbow_hit2.wav
sprites/ricochet/discreturn.spr
sprites/ricochet/weapon_disc.txt
sprites/ricochet/disc1.spr
sprites/ricochet/discgrey.spr
sprites/ricochet/disc2.spr
sprites/ricochet/disctriple.spr
sprites/ricochet/discfast.spr
sprites/ricochet/dischard.spr
sprites/ricochet/discfreeze.spr