maps/svencontra2_1a.bsp
maps/svencontra2_1b.bsp
maps/svencontra2_1a.cfg
maps/svencontra2_1b.cfg
maps/svencontra2_1a_skl.cfg
maps/svencontra2_2a.bsp
maps/svencontra2_2b.bsp
maps/svencontra2_2a.cfg
maps/svencontra2_2b.cfg
maps/svencontra2_2a_skl.cfg
maps/svencontra2.gmr
maps/svencontra2.gsr

models/svencontra2/aatank_shell.mdl
models/svencontra2/flypack.mdl
models/svencontra2/hgrunt.mdl
models/svencontra2/hgrunt_opfor.mdl
models/svencontra2/hgrunt_torch.mdl
models/svencontra2/hwgrunt.mdl
models/svencontra2/turret_shell.mdl
models/svencontra2/v_knife.mdl
models/svencontra2/v_sc2ar.mdl
models/svencontra2/v_sc2fg.mdl
models/svencontra2/v_sc2lg.mdl
models/svencontra2/v_sc2mg.mdl
models/svencontra2/v_sc2sg.mdl
models/svencontra2/wp_knife.mdl
models/svencontra2/wp_sc2ar.mdl
models/svencontra2/wp_sc2fg.mdl
models/svencontra2/wp_sc2lg.mdl
models/svencontra2/wp_sc2mg.mdl
models/svencontra2/wp_sc2sg.mdl
models/svencontra2/w_firstaid.mdl
models/svencontra2/w_pcvarmour.mdl
models/svencontra2/zombie_soldier.mdl
models/svencontra2/stage1/helicopter.mdl
models/svencontra2/stage1/helicopter_ropes.mdl
models/svencontra2/stage1/rampike_01.mdl
models/svencontra2/stage1/rampike_02.mdl
models/svencontra2/stage1/rampike_03.mdl
models/svencontra2/stage1/rampike_04.mdl
models/svencontra2/stage2/apache_idle.mdl
models/svencontra2/stage2/barrel.mdl
models/svencontra2/stage2/howitzer.mdl
models/svencontra2/stage2/militarytruck.mdl
models/svencontra2/stage2/launch_rocket.mdl
models/svencontra2/stage2/mortar_rocket.mdl
models/svencontra2/stage2/palm_a.mdl
models/svencontra2/stage2/palm_b.mdl
models/svencontra2/stage2/pit_drone_big.mdl
models/svencontra2/stage2/rubble.mdl
models/svencontra2/stage2/truck.mdl

sound/svencontra2/stage1/aatank_shot.wav
sound/svencontra2/stage1/ap_rotor2.wav
sound/svencontra2/stage1/sentry_deploy.wav
sound/svencontra2/stage1/sentry_shot.wav
sound/svencontra2/stage1/stage1bgm.wav
sound/svencontra2/stage1/stage1lead.wav
sound/svencontra2/stage1/thunder.wav
sound/svencontra2/stage1/turret_deploy.wav
sound/svencontra2/stage1/turret_shot.wav
sound/svencontra2/stage2/battery.wav
sound/svencontra2/stage2/bomber_move.wav
sound/svencontra2/stage2/bomber_wash.wav
sound/svencontra2/stage2/engine.wav
sound/svencontra2/stage2/liftgate.wav
sound/svencontra2/stage2/motank_hatch.wav
sound/svencontra2/stage2/part_main.wav
sound/svencontra2/stage2/part_sec.wav
sound/svencontra2/stage2/roboarm.wav
sound/svencontra2/stage2/scrbips.wav
sound/svencontra2/stage2/stage2bgm.wav
sound/svencontra2/stage2/stage2lead.wav
sound/svencontra2/1up.wav
sound/svencontra2/areaclear.wav
sound/svencontra2/bossbgm_lead.wav
sound/svencontra2/bossbgm_loop.wav
sound/svencontra2/bossexplo.wav
sound/svencontra2/bullet_hit.wav
sound/svencontra2/buzzer.wav
sound/svencontra2/buzzer2.wav
sound/svencontra2/explo_a.wav
sound/svencontra2/explo_b.wav
sound/svencontra2/flypack.wav
sound/svencontra2/mark.wav
sound/svencontra2/npcdead_a.wav
sound/svencontra2/npcdead_b.wav
sound/svencontra2/npcdead_c.wav
sound/svencontra2/npcdead_d.wav
sound/svencontra2/npcdead_e.wav
sound/svencontra2/picked.wav

sound/weapons/svencontra2/ar_reload.wav
sound/weapons/svencontra2/shot_ar.wav
sound/weapons/svencontra2/shot_fg.wav
sound/weapons/svencontra2/shot_fghit.wav
sound/weapons/svencontra2/shot_gr.wav
sound/weapons/svencontra2/shot_lg.wav
sound/weapons/svencontra2/shot_mg.wav
sound/weapons/svencontra2/shot_sg.wav

sprites/svencontra2/1up.spr
sprites/svencontra2/aim_sprite.spr
sprites/svencontra2/area1name.spr
sprites/svencontra2/area2name.spr
sprites/svencontra2/area2_sprite.spr
sprites/svencontra2/beambrust.spr
sprites/svencontra2/boss_sprite.spr
sprites/svencontra2/bullet_ar.spr
sprites/svencontra2/bullet_fg.spr
sprites/svencontra2/bullet_fghit.spr
sprites/svencontra2/bullet_gr.spr
sprites/svencontra2/bullet_mg.spr
sprites/svencontra2/bullet_sg.spr
sprites/svencontra2/bullet_tta.spr
sprites/svencontra2/bullet_ttb.spr
sprites/svencontra2/bullet_ttc.spr
sprites/svencontra2/bullet_ttd.spr
sprites/svencontra2/bullet_tte.spr
sprites/svencontra2/bullet_ttf.spr
sprites/svencontra2/bullet_ttg.spr
sprites/svencontra2/bullet_tth.spr
sprites/svencontra2/button_sprite.spr
sprites/svencontra2/danger_sprite.spr
sprites/svencontra2/deadspray_a.spr
sprites/svencontra2/deadspray_b.spr
sprites/svencontra2/deadspray_c.spr
sprites/svencontra2/explo_a.spr
sprites/svencontra2/explo_b.spr
sprites/svencontra2/fpexplo.spr
sprites/svencontra2/hud_sc2ar.spr
sprites/svencontra2/hud_sc2fg.spr
sprites/svencontra2/hud_sc2lg.spr
sprites/svencontra2/hud_sc2mg.spr
sprites/svencontra2/hud_sc2sg.spr
sprites/svencontra2/icon_sc2fg.spr
sprites/svencontra2/icon_sc2lg.spr
sprites/svencontra2/icon_sc2mg.spr
sprites/svencontra2/icon_sc2sg.spr
sprites/svencontra2/lgbeam.spr
sprites/svencontra2/lgbeam2.spr
sprites/svencontra2/locat1.spr
sprites/svencontra2/locat2.spr
sprites/svencontra2/mark.spr
sprites/svencontra2/muzx2.spr
sprites/svencontra2/nextarea.spr
sprites/svencontra2/shoot_sprite.spr
sprites/svencontra2/tobecontinued.spr
sprites/svencontra2/weapon_sc2ar.txt
sprites/svencontra2/weapon_sc2fg.txt
sprites/svencontra2/weapon_sc2lg.txt
sprites/svencontra2/weapon_sc2mg.txt
sprites/svencontra2/weapon_sc2sg.txt

scripts/maps/svencontra2/contra2.as
scripts/maps/svencontra2/dynamicdifficult.as
scripts/maps/svencontra2/hook.as
scripts/maps/svencontra2/monsterdeath.as
scripts/maps/svencontra2/point_checkpoint.as
scripts/maps/svencontra2/svencontra.fgd
scripts/maps/svencontra2/utility.as
scripts/maps/svencontra2/entity/func_noprojclip.as
scripts/maps/svencontra2/entity/func_tank_custom.as
scripts/maps/svencontra2/entity/info_weaponflag.as
scripts/maps/svencontra2/entity/weaponballoon.as
scripts/maps/svencontra2/entity/trigger_changesky2.as
scripts/maps/svencontra2/proj/proj_bullet.as
scripts/maps/svencontra2/weapon/weaponbase.as
scripts/maps/svencontra2/weapon/weapon_sc2ar.as
scripts/maps/svencontra2/weapon/weapon_sc2fg.as
scripts/maps/svencontra2/weapon/weapon_sc2lg.as
scripts/maps/svencontra2/weapon/weapon_sc2mg.as
scripts/maps/svencontra2/weapon/weapon_sc2sg.as