// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cs_dust.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
models/player/cs_arctic/cs_arctic.bmp
models/player/cs_arctic/cs_arctic.mdl
models/player/cs_guerilla/cs_guerilla.bmp
models/player/cs_guerilla/cs_guerilla.mdl
models/player/cs_leet/cs_leet.bmp
models/player/cs_leet/cs_leet.mdl
models/player/cs_terror/cs_terror.bmp
models/player/cs_terror/cs_terror.mdl
models/The_Dust/bomb.mdl
models/The_Dust/NPC/GIGN_Mp5.mdl
models/The_Dust/NPC/GIGN_RPG.mdl
models/The_Dust/NPC/GIGN_Shotgun.mdl
models/The_Dust/NPC/GIGN_Sniper.mdl
models/The_Dust/NPC/GSG9_Mp5.mdl
models/The_Dust/NPC/GSG9_RPG.mdl
models/The_Dust/NPC/GSG9_Shotgun.mdl
models/The_Dust/NPC/GSG9_Sniper.mdl
models/The_Dust/NPC/SAS_Mp5.mdl
models/The_Dust/NPC/SAS_RPG.mdl
models/The_Dust/NPC/SAS_Shotgun.mdl
models/The_Dust/NPC/SAS_Sniper.mdl
models/The_Dust/NPC/URBAN_Mp5.mdl
models/The_Dust/NPC/URBAN_RPG.mdl
models/The_Dust/NPC/URBAN_Shotgun.mdl
models/The_Dust/NPC/URBAN_Sniper.mdl
models/The_Dust/NPC/VIP_hwgrunt.mdl
models/The_Dust/p_ak47.mdl
models/The_Dust/p_deagle.mdl
models/The_Dust/p_g3sg1.mdl
models/The_Dust/p_hegrenade.mdl
models/The_Dust/p_knife.mdl
models/The_Dust/p_m249.mdl
models/The_Dust/p_mp5.mdl
models/The_Dust/p_xm1014.mdl
models/The_Dust/v_ak47.mdl
models/The_Dust/v_deagle.mdl
models/The_Dust/v_g3sg1.mdl
models/The_Dust/v_hegrenade.mdl
models/The_Dust/v_knife.mdl
models/The_Dust/v_m249.mdl
models/The_Dust/v_mp5.mdl
models/The_Dust/v_xm1014.mdl
models/The_Dust/w_ak47.mdl
models/The_Dust/w_deagle.mdl
models/The_Dust/w_g3sg1.mdl
models/The_Dust/w_hegrenade.mdl
models/The_Dust/w_knife.mdl
models/The_Dust/w_m249.mdl
models/The_Dust/w_mp5.mdl
models/The_Dust/w_xm1014.mdl
sound/The_Dust/bossbattle.wav
sound/The_Dust/c4plant.wav
sound/The_Dust/okletsgo.wav
sound/The_Dust/weapons/ak47.wav
sound/The_Dust/weapons/ak47_boltpull.wav
sound/The_Dust/weapons/ak47_clipin.wav
sound/The_Dust/weapons/ak47_clipout.wav
sound/The_Dust/weapons/de_clipin.wav
sound/The_Dust/weapons/de_clipout.wav
sound/The_Dust/weapons/deagle.wav
sound/The_Dust/weapons/g3sg1-1.wav
sound/The_Dust/weapons/g3sg1_clipin.wav
sound/The_Dust/weapons/g3sg1_clipout.wav
sound/The_Dust/weapons/g3sg1_slide.wav
sound/The_Dust/weapons/knife_deploy.wav
sound/The_Dust/weapons/knife_hit1.wav
sound/The_Dust/weapons/knife_hit2.wav
sound/The_Dust/weapons/knife_hit3.wav
sound/The_Dust/weapons/knife_hit4.wav
sound/The_Dust/weapons/knife_hitwall1.wav
sound/The_Dust/weapons/knife_slash1.wav
sound/The_Dust/weapons/knife_slash2.wav
sound/The_Dust/weapons/knife_stab.wav
sound/The_Dust/weapons/m249.wav
sound/The_Dust/weapons/m249_boxin.wav
sound/The_Dust/weapons/m249_boxout.wav
sound/The_Dust/weapons/m249_chain.wav
sound/The_Dust/weapons/m249_coverdown.wav
sound/The_Dust/weapons/m249_coverup.wav
sound/The_Dust/weapons/mp5.wav
sound/The_Dust/weapons/mp5_clipin.wav
sound/The_Dust/weapons/mp5_clipout.wav
sound/The_Dust/weapons/mp5_slideback.wav
sound/The_Dust/weapons/reload3.wav
sound/The_Dust/weapons/slideback1.wav
sound/The_Dust/weapons/xm1014.wav
sound/The_Dust/weapons/zoom.wav
sprites/Dust/640_wep1.spr
sprites/Dust/640_wep2.spr
sprites/Dust/640_wep3.spr
sprites/Dust/640_wep4.spr
sprites/Dust/640_wep5.spr
sprites/Dust/640_wep7.spr
sprites/Dust/640_wep8.spr
sprites/Dust/arrow.spr
sprites/Dust/sniper_scope.spr
sprites/dust_weapons/weapon_auto.txt
sprites/dust_weapons/weapon_csak47.txt
sprites/dust_weapons/weapon_csm249.txt
sprites/dust_weapons/weapon_csmp5.txt
sprites/dust_weapons/weapon_deagle.txt
sprites/dust_weapons/weapon_knife.txt
sprites/dust_weapons/weapon_xm1014.txt
