// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/want2bk.tga
gfx/env/want2dn.tga
gfx/env/want2ft.tga
gfx/env/want2lf.tga
gfx/env/want2rt.tga
gfx/env/want2up.tga
models/player/wnt_annie/wnt_annie.bmp
models/player/wnt_annie/wnt_annie.mdl
models/player/wnt_bandit_mex/wnt_bandit_mex.bmp
models/player/wnt_bandit_mex/wnt_bandit_mex.mdl
models/player/wnt_bear/wnt_bear.bmp
models/player/wnt_bear/wnt_bear.mdl
models/player/wnt_colonel/wnt_colonel.bmp
models/player/wnt_colonel/wnt_colonel.mdl
models/player/wnt_cowboy/wnt_cowboy.bmp
models/player/wnt_cowboy/wnt_cowboy.mdl
models/player/wnt_crispen/wnt_crispen.bmp
models/player/wnt_crispen/wnt_crispen.mdl
models/player/wnt_dyndave/wnt_dyndave.bmp
models/player/wnt_dyndave/wnt_dyndave.mdl
models/player/wnt_hoss/wnt_hoss.bmp
models/player/wnt_hoss/wnt_hoss.mdl
models/player/wnt_kaiewi/wnt_kaiewi.bmp
models/player/wnt_kaiewi/wnt_kaiewi.mdl
models/player/wnt_masala/wnt_masala.bmp
models/player/wnt_masala/wnt_masala.mdl
models/player/wnt_miner/wnt_miner.bmp
models/player/wnt_miner/wnt_miner.mdl
models/player/wnt_nagatow/wnt_nagatow.bmp
models/player/wnt_nagatow/wnt_nagatow.mdl
models/player/wnt_ramone/wnt_ramone.bmp
models/player/wnt_ramone/wnt_ramone.mdl
models/player/wnt_rogan/wnt_rogan.bmp
models/player/wnt_rogan/wnt_rogan.mdl
models/player/wnt_townmex/wnt_townmex.bmp
models/player/wnt_townmex/wnt_townmex.mdl
models/player/wnt_twnwest/wnt_twnwest.bmp
models/player/wnt_twnwest/wnt_twnwest.mdl
models/wanted/cactus.mdl
models/wanted/dawsongibs.mdl
models/wanted/dish.mdl
models/wanted/glass.mdl
models/wanted/glassgibs_small.mdl
models/wanted/leech.mdl
models/wanted/p_dynamite.mdl
models/wanted/p_syringe.mdl
models/wanted/pickaxe.mdl
models/wanted/shovel.mdl
models/wanted/skeleton.mdl
models/wanted/smithgibs.mdl
models/wanted/storegibs.mdl
models/wanted/v_dynamite.mdl
models/wanted/v_syringe.mdl
models/wanted/w_battery.mdl
models/wanted/w_dynamite.mdl
models/wanted/w_gattlinggun_belt.mdl
models/wanted/w_medkit.mdl
models/wanted/w_shotbox.mdl
models/wanted/w_syringebox.mdl
models/wanted/w_weaponbox.mdl
models/wanted/wagonwheel.mdl
models/wanted/wheelside.mdl
sound/wanted/colonel/ranch1.wav
sound/wanted/colonel/ranch10.wav
sound/wanted/colonel/ranch11.wav
sound/wanted/colonel/ranch12.wav
sound/wanted/colonel/ranch13.wav
sound/wanted/colonel/ranch14.wav
sound/wanted/colonel/ranch15.wav
sound/wanted/colonel/ranch16.wav
sound/wanted/colonel/ranch2.wav
sound/wanted/colonel/ranch3.wav
sound/wanted/colonel/ranch4.wav
sound/wanted/colonel/ranch5.wav
sound/wanted/colonel/ranch6.wav
sound/wanted/colonel/ranch7.wav
sound/wanted/colonel/ranch8.wav
sound/wanted/colonel/ranch9.wav
sound/wanted/colonel/staked.wav
sound/wanted/items/smallmedkit1.wav
sound/wanted/items/suitchargeok1.wav
sound/wanted/miner/awshit.wav
sound/wanted/miner/dynamite.wav
sound/wanted/miner/getim.wav
sound/wanted/miner/lookout.wav
sound/wanted/miner/mooove.wav
sound/wanted/miner/mooveit.wav
sound/wanted/miner/nooo.wav
sound/wanted/miner/takecover.wav
sound/wanted/miner/watchout.wav
sound/wanted/miner/yehaw.wav
sound/wanted/voice/clint11.wav
sound/wanted/voice/clint48.wav
sound/wanted/voice/gb_greenstick.wav
sound/wanted/voice/gb_hcrit.wav
sound/wanted/voice/gb_hdrop0.wav
sound/wanted/voice/gb_hdrop1.wav
sound/wanted/voice/gb_hkark.wav
sound/wanted/voice/gb_housecall.wav
sound/wanted/voice/gb_leaking.wav
sound/wanted/voice/gb_scorpstg.wav
sound/wanted/voice/gb_scratch.wav
sound/wanted/voice/gb_tasteblood.wav
sound/wanted/voice/gb_tobone.wav
sound/wanted/voice/gb_twisted.wav
sound/wanted/wanted_materials.txt
sound/wanted/world/bird4.wav
sound/wanted/world/frog.wav
sound/wanted/world/largfire.wav
sound/wanted/world/sfire.wav
sprites/wanted/weapon_beartrap.txt
sprites/wanted/weapon_bow.txt
sprites/wanted/weapon_buffalo.txt
sprites/wanted/weapon_cannon.txt
sprites/wanted/weapon_colts.txt
sprites/wanted/weapon_dynamite.txt
sprites/wanted/weapon_gattlinggun.txt
sprites/wanted/weapon_knife.txt
sprites/wanted/weapon_pick.txt
sprites/wanted/weapon_pistol.txt
sprites/wanted/weapon_scorpion.txt
sprites/wanted/weapon_want_shotgun.txt
sprites/wanted/weapon_winchester.txt
wanted.wad
